# Reference setup data for matching employee bank and address fields.

province_name_groups = {
    "Ha Noi City": [
        "Ha Noi", "Hanoi", "Hà Nội"
    ],

    "Bac Ninh Province": [
        "Bac Ninh", "Bắc Ninh", "Bac Giang", "Bắc Giang"
    ],

    "Quang Ninh Province": [
        "Quang Ninh", "Quảng Ninh"
    ],

    "Hai Phong City": [
        "Hai Phong", "Hải Phòng", "Hai Duong", "Hải Dương"
    ],

    "Hung Yen Province": [
        "Hung Yen", "Hưng Yên", "Thai Binh", "Thái Bình"
    ],

    "Ninh Binh Province": [
        "Ninh Binh", "Ninh Bình", "Ha Nam", "Hà Nam",
        "Nam Dinh", "Nam Định"
    ],

    "Cao Bang Province": [
        "Cao Bang", "Cao Bằng"
    ],

    "Tuyen Quang Province": [
        "Tuyen Quang", "Tuyên Quang", "Ha Giang", "Hà Giang"
    ],

    "Lao Cai Province": [
        "Lao Cai", "Lào Cai", "Yen Bai", "Yên Bái"
    ],

    "Thai Nguyen Province": [
        "Thai Nguyen", "Thái Nguyên", "Bac Kan", "Bắc Kạn"
    ],

    "Lang Son Province": [
        "Lang Son", "Lạng Sơn"
    ],

    "Phu Tho Province": [
        "Phu Tho", "Phú Thọ", "Vinh Phuc", "Vĩnh Phúc",
        "Hoa Binh", "Hòa Bình"
    ],

    "Dien Bien Province": [
        "Dien Bien", "Điện Biên"
    ],

    "Lai Chau Province": [
        "Lai Chau", "Lai Châu"
    ],

    "Son La Province": [
        "Son La", "Sơn La"
    ],

    "Thanh Hoa Province": [
        "Thanh Hoa", "Thanh Hóa"
    ],

    "Nghe An Province": [
        "Nghe An", "Nghệ An"
    ],

    "Ha Tinh Province": [
        "Ha Tinh", "Hà Tĩnh"
    ],

    "Quang Tri Province": [
        "Quang Tri", "Quảng Trị", "Quang Binh", "Quảng Bình"
    ],

    "Hue City": [
        "Hue", "Huế", "Thua Thien Hue", "Thừa Thiên Huế"
    ],

    "Da Nang City": [
        "Da Nang", "Đà Nẵng", "Quang Nam", "Quảng Nam"
    ],

    "Quang Ngai Province": [
        "Quang Ngai", "Quảng Ngãi", "Kon Tum"
    ],

    "Khanh Hoa Province": [
        "Khanh Hoa", "Khánh Hòa", "Ninh Thuan", "Ninh Thuận"
    ],

    "Gia Lai Province": [
        "Gia Lai", "Binh Dinh", "Bình Định"
    ],

    "Dak Lak Province": [
        "Dak Lak", "Đắk Lắk", "Dac Lak", "Đắc Lắc",
        "Phu Yen", "Phú Yên"
    ],

    "Lam Dong Province": [
        "Lam Dong", "Lâm Đồng", "Dak Nong", "Đắk Nông",
        "Dac Nong", "Binh Thuan", "Bình Thuận"
    ],

    "Tay Ninh Province": [
        "Tay Ninh", "Tây Ninh", "Long An"
    ],

    "Dong Nai Province": [
        "Dong Nai", "Đồng Nai", "Binh Phuoc", "Bình Phước"
    ],

    "Ho Chi Minh City": [
        "Ho Chi Minh", "Hồ Chí Minh", "HCMC", "TPHCM",
        "TP HCM", "Thanh pho Ho Chi Minh", "Thành phố Hồ Chí Minh",
        "Sai Gon", "Sài Gòn", "Saigon",
        "Binh Duong", "Bình Dương",
        "Ba Ria Vung Tau", "Bà Rịa Vũng Tàu",
        "Ba Ria - Vung Tau", "BRVT", "Vung Tau", "Vũng Tàu"
    ],

    "Vinh Long Province": [
        "Vinh Long", "Vĩnh Long", "Ben Tre", "Bến Tre",
        "Tra Vinh", "Trà Vinh"
    ],

    "Dong Thap Province": [
        "Dong Thap", "Đồng Tháp", "Tien Giang", "Tiền Giang"
    ],

    "An Giang Province": [
        "An Giang", "Kien Giang", "Kiên Giang"
    ],

    "Can Tho City": [
        "Can Tho", "Cần Thơ", "Soc Trang", "Sóc Trăng",
        "Hau Giang", "Hậu Giang"
    ],

    "Ca Mau Province": [
        "Ca Mau", "Cà Mau", "Bac Lieu", "Bạc Liêu"
    ],
}


def make_province_aliases(province_name_groups):
    alias_dict = {}

    prefixes = [
        "Tinh", "Tỉnh",
        "TP", "TP.", "Tp", "Tp.",
        "Thanh pho", "Thành phố"
    ]

    suffixes = [
        "Province", "City"
    ]

    for canonical, names in province_name_groups.items():
        aliases = set()

        canonical_base = (
            canonical
            .replace(" Province", "")
            .replace(" City", "")
            .strip()
        )

        all_names = list(names) + [canonical, canonical_base]

        for name in all_names:
            aliases.add(name)

            for prefix in prefixes:
                aliases.add(f"{prefix} {name}")

            for suffix in suffixes:
                aliases.add(f"{name} {suffix}")

        alias_dict[canonical] = sorted(aliases)

    return alias_dict


province_old_to_new_alias = make_province_aliases(province_name_groups)
bank_aliases = {
    "Advanced Bank of Asia Limited": [
        "ABA", "ABA Bank", "Advanced Bank of Asia"
    ],

    "BANCO DE ORO": [
        "BDO", "BDO Bank", "BDO Unibank", "Banco De Oro"
    ],

    "Bank of China": [
        "BOC", "BOC Bank", "Bank China"
    ],

    "Cake by VPBank": [
        "Cake", "Cake VPBank", "Cake by VP Bank"
    ],

    "COMMONWEALTH BANK OF AUSTRALIA (CBA)": [
        "CBA", "Commonwealth Bank", "Commonwealth Bank of Australia"
    ],

    "INGDIRECT": [
        "ING", "ING Direct", "ING Bank"
    ],

    "MUFG BANK,LTD.": [
        "MUFG", "MUFG Bank", "Mitsubishi UFJ", "Bank of Tokyo Mitsubishi UFJ"
    ],

    "NEDBANK": [
        "Nedbank", "Ned Bank"
    ],

    "NGAN HANG TMCP NAM A": [
        "Nam A", "Nam A Bank", "NAMA Bank", "NH Nam A",
        "Ngan Hang Nam A", "Ngân hàng Nam Á"
    ],

    "NH CITIBANK (CITIBANK)": [
        "Citi", "Citi Bank", "Citibank", "NH Citibank"
    ],

    "NH NN VA PT NONG THON VN (AGRIBANK)": [
        "Agribank", "Agri Bank", "NH Nong Nghiep",
        "Ngan hang Nong nghiep", "Ngân hàng Nông nghiệp",
        "Vietnam Bank for Agriculture"
    ],

    "NH TMCP PHAT TRIEN TP HCM (HDBANK)": [
        "HDBank", "HD Bank", "HDB", "NH Phat Trien TPHCM",
        "Ngân hàng Phát triển TP HCM"
    ],

    "NH TMCP XUAT NHAP KHAU (EXIMBANK)": [
        "Eximbank", "Exim Bank", "EIB",
        "Export Import Bank", "NH Xuat Nhap Khau"
    ],

    "NH TNHH MTV UNITED OVERSEAS VIETNAM": [
        "UOB", "UOB Vietnam", "United Overseas Bank"
    ],

    "NHTMCP A CHAU (ACB)": [
        "ACB", "A Chau Bank", "Asia Commercial Bank",
        "NH A Chau", "Ngân hàng Á Châu"
    ],

    "NHTMCP AN BINH (ABBANK)": [
        "ABBANK", "ABBank", "An Binh Bank", "NH An Binh",
        "Ngân hàng An Bình"
    ],

    "NHTMCP Ban Viet": [
        "Ban Viet", "Ban Viet Bank", "BVB",
        "Viet Capital Bank", "Ngân hàng Bản Việt"
    ],

    "NHTMCP CONG THUONG VN (VIETINBANK)": [
        "Vietinbank", "Vietin Bank", "CTG", "Incombank",
        "NH Cong Thuong", "Ngân hàng Công Thương"
    ],

    "NHTMCP DAU TU VA PT VN (BIDV)": [
        "BIDV", "NH Dau Tu", "NH Dau Tu Va Phat Trien",
        "Bank for Investment and Development of Vietnam"
    ],

    "NHTMCP DONG A (DONG A BANK)": [
        "Dong A", "DongA Bank", "Dong A Bank", "DAB",
        "Ngân hàng Đông Á"
    ],

    "NHTMCP DONG NAM A (SEABANK)": [
        "SeABank", "SEA Bank", "Seabank", "Dong Nam A Bank",
        "Ngân hàng Đông Nam Á"
    ],

    "NHTMCP HANG HAI (MARITIME BANK)": [
        "Maritime Bank", "MSB", "MSB Bank",
        "Vietnam Maritime Bank", "NH Hang Hai"
    ],

    "NHTMCP KY THUONG VN (TECHCOMBANK)": [
        "Techcombank", "Techcom Bank", "TCB", "Techcom",
        "NH Ky Thuong", "Ngân hàng Kỹ Thương"
    ],

    "NHTMCP NGOAI THUONG VN (VIETCOMBANK)": [
        "Vietcombank", "Vietcom Bank", "VCB",
        "NH Ngoai Thuong", "Ngân hàng Ngoại Thương"
    ],

    "NHTMCP PHUONG DONG (OCB)": [
        "OCB", "Orient Commercial Bank", "Phuong Dong Bank",
        "Ngân hàng Phương Đông"
    ],

    "NHTMCP QUAN DOI (MB BANK)": [
        "MB", "MBB", "MB Bank", "Military Bank",
        "NH Quan Doi", "Ngân hàng Quân Đội"
    ],

    "NHTMCP QUOC TE VN (VN INTERNATION BANK)": [
        "VIB", "VIB Bank", "Vietnam International Bank",
        "NH Quoc Te", "Ngân hàng Quốc Tế"
    ],

    "NHTMCP SAI GON THUONG TIN (SACOMBANK)": [
        "Sacombank", "Sacombank Bank", "STB",
        "Sai Gon Thuong Tin", "Sài Gòn Thương Tín"
    ],

    "NHTMCP Saigon Hanoi (SHB)": [
        "SHB", "SHB Bank", "Saigon Hanoi Bank",
        "Sai Gon Ha Noi Bank", "Sài Gòn Hà Nội"
    ],

    "NHTMCP TIEN PHONG (TIEN PHONG BANK)": [
        "TPBank", "TP Bank", "TPB", "Tien Phong Bank",
        "Ngân hàng Tiên Phong"
    ],

    "NHTNHH MTV HSBC VN (HSBC BANK VN LTD.)": [
        "HSBC Vietnam", "HSBC VN", "HSBC Bank Vietnam", "HSBC Bank VN"
    ],

    "NHTNHH MTV SHINHAN VN (SHINHAN BANK VN)": [
        "Shinhan", "Shinhan Bank", "Shinhan Vietnam", "Shinhan VN"
    ],

    "NHTNHH MTV STANDARD CHARTERED VN": [
        "Standard Chartered", "Standard Chartered Bank",
        "Standard Chartered Vietnam", "Standard Chartered VN"
    ],

    "Sai Gon Joint Stock Commercial Bank (SCB)": [
        "Sai Gon Commercial Bank", "Saigon Commercial Bank",
        "SCB Vietnam", "SCB VN"
    ],

    "SIAM COMMERCIAL BANK PCL (SCB)": [
        "Siam Commercial Bank", "Siam Commercial Bank PCL",
        "SCB Thailand", "SCB Thai"
    ],

    "The Hongkong and Shanghai Banking Corporation Limited": [
        "Hongkong Shanghai Banking Corporation",
        "The Hongkong and Shanghai Banking Corporation",
        "Hongkong and Shanghai Bank"
    ],

    "VP Bank": [
        "VPBank", "VP Bank", "VPB", "Vietnam Prosperity Bank",
        "Ngân hàng Việt Nam Thịnh Vượng"
    ],
}
banks = ['Advanced Bank of Asia Limited',
 'BANCO DE ORO',
 'Bank of China',
 'Cake by VPBank',
 'COMMONWEALTH BANK OF AUSTRALIA (CBA)',
 'INGDIRECT',
 'MUFG BANK,LTD.',
 'NEDBANK',
 'NGAN HANG TMCP NAM A',
 'NH CITIBANK (CITIBANK)',
 'NH NN VA PT NONG THON VN (AGRIBANK)',
 'NH TMCP PHAT TRIEN TP HCM (HDBANK)',
 'NH TMCP XUAT NHAP KHAU (EXIMBANK)',
 'NH TNHH MTV UNITED OVERSEAS VIETNAM',
 'NHTMCP A CHAU (ACB)',
 'NHTMCP AN BINH (ABBANK)',
 'NHTMCP Ban Viet',
 'NHTMCP CONG THUONG VN (VIETINBANK)',
 'NHTMCP DAU TU VA PT VN (BIDV)',
 'NHTMCP DONG A (DONG A BANK)',
 'NHTMCP DONG NAM A (SEABANK)',
 'NHTMCP HANG HAI (MARITIME BANK)',
 'NHTMCP KY THUONG VN (TECHCOMBANK)',
 'NHTMCP NGOAI THUONG VN (VIETCOMBANK)',
 'NHTMCP PHUONG DONG (OCB)',
 'NHTMCP QUAN DOI (MB BANK)',
 'NHTMCP QUOC TE VN (VN INTERNATION BANK)',
 'NHTMCP SAI GON THUONG TIN (SACOMBANK)',
 'NHTMCP Saigon Hanoi (SHB)',
 'NHTMCP TIEN PHONG (TIEN PHONG BANK)',
 'NHTNHH MTV HSBC VN (HSBC BANK VN LTD.)',
 'NHTNHH MTV SHINHAN VN (SHINHAN BANK VN)',
 'NHTNHH MTV STANDARD CHARTERED VN',
 'Sai Gon Joint Stock Commercial Bank (SCB)',
 'SIAM COMMERCIAL BANK PCL (SCB)',
 'The Hongkong and Shanghai Banking Corporation Limited',
 'VP Bank']

provinces = ['Ha Noi City',
 'Bac Ninh Province',
 'Quang Ninh Province',
 'Hai Phong City',
 'Hung Yen Province',
 'Ninh Binh Province',
 'Cao Bang Province',
 'Tuyen Quang Province',
 'Lao Cai Province',
 'Thai Nguyen Province',
 'Lang Son Province',
 'Phu Tho Province',
 'Dien Bien Province',
 'Lai Chau Province',
 'Son La Province',
 'Thanh Hoa Province',
 'Nghe An Province',
 'Ha Tinh Province',
 'Quang Tri Province',
 'Hue City',
 'Da Nang City',
 'Quang Ngai Province',
 'Khanh Hoa Province',
 'Gia Lai Province',
 'Dak Lak Province',
 'Lam Dong Province',
 'Tay Ninh Province',
 'Dong Nai Province',
 'Ho Chi Minh City',
 'Vinh Long Province',
 'Dong Thap Province',
 'An Giang Province',
 'Can Tho City',
 'Ca Mau Province']

wards = ['Ward',
 'My Huong Ward',
 'My Phuoc Ward',
 'My Quoi Ward',
 'My Tu Ward',
 'My Xuyen Ward',
 'Nga Bay Ward',
 'Nga Nam Ward',
 'Ngoc To Ward',
 'Nhon Ai Ward',
 'Nhon My Ward',
 'Nhu Gia Ward',
 'Ninh Kieu Ward',
 'O Mon Ward',
 'Phong Dien Ward',
 'Phong Nam Ward',
 'Phu Huu Ward',
 'Phu Loc Ward',
 'Phu Loi Ward',
 'Phu Tam Ward',
 'Phung Hiep Ward',
 'Phuoc Thoi Ward',
 'Phuong Binh Ward',
 'Soc Trang Ward',
 'An Binh Ward',
 'An Lac Thon Ward',
 'An Ninh Ward',
 'An Thanh Ward',
 'Binh Thuy Ward',
 'Cai Khe Ward',
 'Cai Rang Ward',
 'Chau Thanh Ward',
 'Co Do Ward',
 'Cu Lao Dung Ward',
 'Dai Hai Ward',
 'Dai Ngai Ward',
 'Dai Thanh Ward',
 'Dong Hiep Ward',
 'Dong Phuoc Ward',
 'Dong Thuan Ward',
 'Tai Van Ward',
 'Tan An Ward',
 'Tan Binh Ward',
 'Tan Hoa Ward',
 'Tan Loc Ward',
 'Tan Long Ward',
 'Tan Phuoc Hung Ward',
 'Tan Thanh Ward',
 'Thanh An Ward',
 'Thanh Hoa Ward',
 'Thanh Phu Ward',
 'Thanh Quoi Ward',
 'Thanh Thoi An Ward',
 'Thanh Xuan Ward',
 'Thoi An Dong Ward',
 'Thoi An Hoi Ward',
 'Thoi Hung Ward',
 'Thoi Lai Ward',
 'Thoi Long Ward',
 'Thot Not Ward',
 'Thuan Hoa Ward',
 'Thuan Hung Ward',
 'Tran De Ward',
 'Trung Hung Ward',
 'Trung Nhut Ward',
 'Truong Khanh Ward',
 'Truong Long Ward',
 'Truong Long Tay Ward',
 'Truong Thanh Ward',
 'Truong Xuan Ward',
 'Vi Tan Ward',
 'Vi Thanh Ward',
 'Vi Thanh 1 Ward',
 'Vi Thuy Ward',
 'Vinh Chau Ward',
 'Vinh Hai Ward',
 'Gia Hoa Ward',
 'Hiep Hung Ward',
 'Ho Dac Kien Ward',
 'Hoa An Ward',
 'Hoa Luu Ward',
 'Hoa Tu Ward',
 'Hung Phu Ward',
 'Ke Sach Ward',
 'Khanh Hoa Ward',
 'Lai Hoa Ward',
 'Lam Tan Ward',
 'Lich Hoi Thuong Ward',
 'Lieu Tu Ward',
 'Long Binh Ward',
 'Long Hung Ward',
 'Long My Ward',
 'Long Phu Ward',
 'Long Phu 1 Ward',
 'Long Tuyen Ward',
 'Luong Tam Ward',
 'Vinh Loi Ward',
 'Vinh Phuoc Ward',
 'Vinh Thanh Ward',
 'Vinh Thuan Dong Ward',
 'Vinh Trinh Ward',
 'Vinh Tuong Ward',
 'Vinh Vien Ward',
 'Xa Phien Ward',
 'Nam Giang Ward',
 'Nam Phuoc Ward',
 'Nam Tra My Ward',
 'Ngu Hanh Son Ward',
 'Nong Son Ward',
 'Nui Thanh Ward',
 'Phu Ninh Ward',
 'Phu Thuan Ward',
 'Phuoc Chanh Ward',
 'Phuoc Hiep Ward',
 'Phuoc Nang Ward',
 'Phuoc Thanh Ward',
 'Phuoc Tra Ward',
 'Quang Phu Ward',
 'Que Phuoc Ward',
 'Que Son Ward',
 'Que Son Trung Ward',
 'Son Cam Ha Ward',
 'Son Tra Ward',
 'Song Kon Ward',
 'Song Vang Ward',
 'An Hai Ward',
 'An Khe Ward',
 'An Thang Ward',
 'Avuong Ward',
 'Ba Na Ward',
 'Ban Thach Ward',
 'Ben Giang Ward',
 'Ben Hien Ward',
 'Cam Le Ward',
 'Chien Dan Ward',
 'Hoang Sa Ward',
 'Dac Pring Ward',
 'Dai Loc Ward',
 'Dien Ban Ward',
 'Dien Ban Bac Ward',
 'Dien Ban Dong Ward',
 'Dien Ban Tay Ward',
 'Dong Duong Ward',
 'Dong Giang Ward',
 'Tam Anh Ward',
 'Tam Hai Ward',
 'Tam Ky Ward',
 'Tam My Ward',
 'Tam Xuan Ward',
 'Tan Hiep Ward',
 'Tay Giang Ward',
 'Tay Ho Ward',
 'Thang An Ward',
 'Thang Binh Ward',
 'Thang Dien Ward',
 'Thang Phu Ward',
 'Thang Truong Ward',
 'Thanh Binh Ward',
 'Thanh Khe Ward',
 'Thanh My Ward',
 'Thu Bon Ward',
 'Thuong Duc Ward',
 'Tien Phuoc Ward',
 'Tra Doc Ward',
 'Tra Giap Ward',
 'Tra Leng Ward',
 'Tra Lien Ward',
 'Tra Linh Ward',
 'Tra My Ward',
 'Tra Tan Ward',
 'Tra Tap Ward',
 'Tra Van Ward',
 'Viet An Ward',
 'Duc Phu Ward',
 'Duy Nghia Ward',
 'Duy Xuyen Ward',
 'Go Noi Ward',
 'Ha Nha Ward',
 'Hai Chau Ward',
 'Hai Van Ward',
 'Hiep Duc Ward',
 'Hoa Cuong Ward',
 'Hoa Khanh Ward',
 'Hoa Tien Ward',
 'Hoa Vang Ward',
 'Hoa Xuan Ward',
 'Hoi An Ward',
 'Hoi An Dong Ward',
 'Hoi An Tay Ward',
 'Hung Son Ward',
 'Huong Tra Ward',
 'Kham Duc Ward',
 'La Dee Ward',
 'La Ee Ward',
 'Lanh Ngoc Ward',
 'Lien Chieu Ward',
 'Vu Gia Ward',
 'Xuan Phu Ward',
 'My Duc Ward',
 'Nam Phu Ward',
 'Nghia Do Ward',
 'Ngoc Ha Ward',
 'Ngoc Hoi Ward',
 'Noi Bai Ward',
 'O Cho Dua Ward',
 'O Dien Ward',
 'Phu Cat Ward',
 'Phu Dien Ward',
 'Phu Dong Ward',
 'Phu Luong Ward',
 'Phu Nghia Ward',
 'Phu Thuong Ward',
 'Phu Xuyen Ward',
 'Phuc Loc Ward',
 'Phuc Loi Ward',
 'Phuc Son Ward',
 'Phuc Thinh Ward',
 'Phuc Tho Ward',
 'Phuong Duc Ward',
 'Phuong Liet Ward',
 'Quang Bi Ward',
 'Quang Minh Ward',
 'Quang Oai Ward',
 'Quoc Oai Ward',
 'Soc Son Ward',
 'Son Dong Ward',
 'Son Tay Ward',
 'Suoi Hai Ward',
 'An Khanh Ward',
 'Ba Dinh Ward',
 'Ba Vi Ward',
 'Bach Mai Ward',
 'Bat Bat Ward',
 'Bat Trang Ward',
 'Binh Minh Ward',
 'Bo De Ward',
 'Cau Giay Ward',
 'Chuong Duong Ward',
 'Chuong My Ward',
 'Chuyen My Ward',
 'Co Do Ward',
 'Cua Nam Ward',
 'Da Phuc Ward',
 'Dai Mo Ward',
 'Dai Thanh Ward',
 'Dai Xuyen Ward',
 'Dan Hoa Ward',
 'Dan Phuong Ward',
 'Dinh Cong Ward',
 'Doai Phuong Ward',
 'Dong Anh Ward',
 'Dong Da Ward',
 'Dong Ngac Ward',
 'Tam Hung Ward',
 'Tay Ho Ward',
 'Tay Mo Ward',
 'Tay Phuong Ward',
 'Tay Tuu Ward',
 'Thach That Ward',
 'Thanh Liet Ward',
 'Thanh Oai Ward',
 'Thanh Tri Ward',
 'Thanh Xuan Ward',
 'Thien Loc Ward',
 'Thu Lam Ward',
 'Thuan An Ward',
 'Thuong Cat Ward',
 'Thuong Phuc Ward',
 'Thuong Tin Ward',
 'Tien Thang Ward',
 'Tran Phu Ward',
 'Trung Gia Ward',
 'Tu Liem Ward',
 'Tung Thien Ward',
 'Tuong Mai Ward',
 'Ung Hoa Ward',
 'Ung Thien Ward',
 'Van Dinh Ward',
 'Van Mieu - Quoc Tu Giam Ward',
 'Vat Lai Ward',
 'Viet Hung Ward',
 'Duong Hoa Ward',
 'Duong Noi Ward',
 'Gia Lam Ward',
 'Giang Vo Ward',
 'Ha Bang Ward',
 'Ha Dong Ward',
 'Hai Ba Trung Ward',
 'Hat Mon Ward',
 'Hoa Lac Ward',
 'Hoa Phu Ward',
 'Hoa Xa Ward',
 'Hoai Duc Ward',
 'Hoan Kiem Ward',
 'Hoang Liet Ward',
 'Hoang Mai Ward',
 'Hong Ha Ward',
 'Hong Son Ward',
 'Hong Van Ward',
 'Hung Dao Ward',
 'Huong Son Ward',
 'Khuong Dinh Ward',
 'Kien Hung Ward',
 'Kieu Phu Ward',
 'Kim Anh Ward',
 'Kim Lien Ward',
 'Lang Ward',
 'Lien Minh Ward',
 'Linh Nam Ward',
 'Long Bien Ward',
 'Me Linh Ward',
 'Minh Chau Ward',
 'Vinh Hung Ward',
 'Vinh Thanh Ward',
 'Vinh Tuy Ward',
 'Xuan Dinh Ward',
 'Xuan Mai Ward',
 'Xuan Phuong Ward',
 'Yen Bai Ward',
 'Yen Hoa Ward',
 'Yen Lang Ward',
 'Yen Nghia Ward',
 'Yen So Ward',
 'Yen Xuan Ward',
 'Nam An Phu Ward',
 'Nam Do Son Ward',
 'Nam Dong Ward',
 'Nam Sach Ward',
 'Nam Thanh Mien Ward',
 'Nam Trieu Ward',
 'Nghi Duong Ward',
 'Ngo Quyen Ward',
 'Nguyen Binh Khiem Ward',
 'Nguyen Dai Nang Ward',
 'Nguyen Giap Ward',
 'Nguyen Luong Bang Ward',
 'Nguyen Trai Ward',
 'Nhi Chieu Ward',
 'Ninh Giang Ward',
 'Pham Su Manh Ward',
 'Phu Lien Ward',
 'Phu Thai Ward',
 'Quyet Thang Ward',
 'Ai Quoc Ward',
 'An Bien Ward',
 'An Duong Ward',
 'An Hai Ward',
 'An Hung Ward',
 'An Khanh Ward',
 'An Lao Ward',
 'An Phong Ward',
 'An Phu Ward',
 'An Quang Ward',
 'An Thanh Ward',
 'An Truong Ward',
 'Bac An Phu Ward',
 'Bac Thanh Mien Ward',
 'Bach Dang Ward',
 'Binh Giang Ward',
 'Cam Giang Ward',
 'Cam Giang Ward',
 'Chan Hung Ward',
 'Chi Linh Ward',
 'Chi Minh Ward',
 'Chu Van An Ward',
 'Bach Long Vi Ward',
 'Cat Hai Ward',
 'Dai Son Ward',
 'Do Son Ward',
 'Dong Hai Ward',
 'Tan An Ward',
 'Tan Hung Ward',
 'Tan Ky Ward',
 'Tan Minh Ward',
 'Thach Khoi Ward',
 'Thai Tan Ward',
 'Thanh Dong Ward',
 'Thanh Ha Ward',
 'Thanh Mien Ward',
 'Thien Huong Ward',
 'Thuong Hong Ward',
 'Thuy Nguyen Ward',
 'Tien Lang Ward',
 'Tien Minh Ward',
 'Tran Hung Dao Ward',
 'Tran Lieu Ward',
 'Tran Nhan Tong Ward',
 'Tran Phu Ward',
 'Truong Tan Ward',
 'Tu Ky Ward',
 'Tu Minh Ward',
 'Tue Tinh Ward',
 'Viet Hoa Ward',
 'Viet Khe Ward',
 'Vinh Am Ward',
 'Vinh Bao Ward',
 'Vinh Hai Ward',
 'Duong An Ward',
 'Duong Kinh Ward',
 'Gia Loc Ward',
 'Gia Phuc Ward',
 'Gia Vien Ward',
 'Ha Bac Ward',
 'Ha Dong Ward',
 'Ha Nam Ward',
 'Ha Tay Ward',
 'Hai An Ward',
 'Hai Duong Ward',
 'Hai Hung Ward',
 'Hoa Binh Ward',
 'Hong An Ward',
 'Hong Bang Ward',
 'Hong Chau Ward',
 'Hop Tien Ward',
 'Hung Dao Ward',
 'Hung Thang Ward',
 'Ke Sat Ward',
 'Khuc Thua Du Ward',
 'Kien An Ward',
 'Kien Hai Ward',
 'Kien Hung Ward',
 'Kien Minh Ward',
 'Kien Thuy Ward',
 'Kim Thanh Ward',
 'Kinh Mon Ward',
 'Lac Phuong Ward',
 'Lai Khe Ward',
 'Le Chan Ward',
 'Le Dai Hanh Ward',
 'Le Ich Moc Ward',
 'Le Thanh Nghi Ward',
 'Luu Kiem Ward',
 'Mao Dien Ward',
 'Vinh Hoa Ward',
 'Vinh Lai Ward',
 'Vinh Thinh Ward',
 'Vinh Thuan Ward',
 'Yet Kieu Ward',
 'Minh Phung Ward',
 'Minh Thanh Ward',
 'Ngai Giao Ward',
 'Nghia Thanh Ward',
 'Nha Be Ward',
 'Nhieu Loc Ward',
 'Nhuan Duc Ward',
 'Phu An Ward',
 'Phu Dinh Ward',
 'Phu Giao Ward',
 'Phu Hoa Dong Ward',
 'Phu Lam Ward',
 'Phu Loi Ward',
 'Phu My Ward',
 'Phu Nhuan Ward',
 'Phu Thanh Ward',
 'Phu Tho Ward',
 'Phu Tho Hoa Ward',
 'Phu Thuan Ward',
 'Phuoc Hai Ward',
 'Phuoc Hoa Ward',
 'Phuoc Long Ward',
 'Phuoc Thang Ward',
 'Phuoc Thanh Ward',
 'Rach Dua Ward',
 'Sai Gon Ward',
 'An Dong Ward',
 'An Hoi Dong Ward',
 'An Hoi Tay Ward',
 'An Khanh Ward',
 'An Lac Ward',
 'An Long Ward',
 'An Nhon Ward',
 'An Nhon Tay Ward',
 'An Phu Ward',
 'An Phu Dong Ward',
 'An Thoi Dong Ward',
 'Ba Diem Ward',
 'Ba Ria Ward',
 'Bac Tan Uyen Ward',
 'Ban Co Ward',
 'Bau Bang Ward',
 'Bau Lam Ward',
 'Bay Hien Ward',
 'Ben Cat Ward',
 'Ben Thanh Ward',
 'Binh Chanh Ward',
 'Binh Chau Ward',
 'Binh Co Ward',
 'Binh Dong Ward',
 'Binh Duong Ward',
 'Binh Gia Ward',
 'Binh Hoa Ward',
 'Binh Hung Ward',
 'Binh Hung Hoa Ward',
 'Binh Khanh Ward',
 'Binh Loi Ward',
 'Binh Loi Trung Ward',
 'Binh My Ward',
 'Binh Phu Ward',
 'Binh Quoi Ward',
 'Binh Tan Ward',
 'Binh Tay Ward',
 'Binh Thanh Ward',
 'Binh Thoi Ward',
 'Binh Tien Ward',
 'Binh Tri Dong Ward',
 'Binh Trung Ward',
 'Can Gio Ward',
 'Cat Lai Ward',
 'Cau Kieu Ward',
 'Cau Ong Lanh Ward',
 'Chanh Hiep Ward',
 'Chanh Hung Ward',
 'Chanh Phu Hoa Ward',
 'Chau Duc Ward',
 'Chau Pha Ward',
 'Cho Lon Ward',
 'Cho Quan Ward',
 'Cu Chi Ward',
 'Con Dao Ward',
 'Dat Do Ward',
 'Dau Tieng Ward',
 'Di An Ward',
 'Dien Hong Ward',
 'Dong Hoa Ward',
 'Dong Hung Thuan Ward',
 'Dong Thanh Ward',
 'Tam Binh Ward',
 'Tam Long Ward',
 'Tam Thang Ward',
 'Tan An Hoi Ward',
 'Tan Binh Ward',
 'Tan Dinh Ward',
 'Tan Dong Hiep Ward',
 'Tan Hai Ward',
 'Tan Hiep Ward',
 'Tan Hoa Ward',
 'Tan Hung Ward',
 'Tan Khanh Ward',
 'Tan My Ward',
 'Tan Nhut Ward',
 'Tan Phu Ward',
 'Tan Phuoc Ward',
 'Tan Son Ward',
 'Tan Son Hoa Ward',
 'Tan Son Nhat Ward',
 'Tan Son Nhi Ward',
 'Tan Tao Ward',
 'Tan Thanh Ward',
 'Tan Thoi Hiep Ward',
 'Tan Thuan Ward',
 'Tan Uyen Ward',
 'Tan Vinh Loc Ward',
 'Tang Nhon Phu Ward',
 'Tay Nam Ward',
 'Tay Thanh Ward',
 'Thai My Ward',
 'Thanh An Ward',
 'Thanh An Ward',
 'Thanh My Tay Ward',
 'Thoi An Ward',
 'Thoi Hoa Ward',
 'Thong Tay Hoi Ward',
 'Thu Dau Mot Ward',
 'Thu Duc Ward',
 'Thuan An Ward',
 'Thuan Giao Ward',
 'Thuong Tan Ward',
 'Tru Van Tho Ward',
 'Trung My Tay Ward',
 'Duc Nhuan Ward',
 'Gia Dinh Ward',
 'Go Vap Ward',
 'Hanh Thong Ward',
 'Hiep Binh Ward',
 'Hiep Phuoc Ward',
 'Ho Tram Ward',
 'Hoa Binh Ward',
 'Hoa Hiep Ward',
 'Hoa Hoi Ward',
 'Hoa Hung Ward',
 'Hoa Loi Ward',
 'Hoc Mon Ward',
 'Hung Long Ward',
 'Khanh Hoi Ward',
 'Kim Long Ward',
 'Lai Thieu Ward',
 'Linh Xuan Ward',
 'Long Binh Ward',
 'Long Dien Ward',
 'Long Hai Ward',
 'Long Hoa Ward',
 'Long Huong Ward',
 'Long Nguyen Ward',
 'Long Phuoc Ward',
 'Long Son Ward',
 'Long Truong Ward',
 'Vinh Hoi Ward',
 'Vinh Loc Ward',
 'Vinh Tan Ward',
 'Vung Tau Ward',
 'Vuon Lai Ward',
 'Xom Chieu Ward',
 'Xuan Hoa Ward',
 'Xuan Son Ward',
 'Xuan Thoi Son Ward',
 'Xuyen Moc Ward',
 'My Thuong Ward',
 'Nam Dong Ward',
 'Phong Dien Ward',
 'Phong Dinh Ward',
 'Phong Phu Ward',
 'Phong Quang Ward',
 'Phong Thai Ward',
 'Phu Bai Ward',
 'Phu Ho Ward',
 'Phu Loc Ward',
 'Phu Vang Ward',
 'Phu Vinh Ward',
 'Phu Xuan Ward',
 'Quang Dien Ward',
 'A Luoi 1 Ward',
 'A Luoi 2 Ward',
 'A Luoi 3 Ward',
 'A Luoi 4 Ward',
 'A Luoi 5 Ward',
 'An Cuu Ward',
 'Binh Dien Ward',
 'Chan May - Lang Co Ward',
 'Dan Dien Ward',
 'Thanh Thuy Ward',
 'Thuan An Ward',
 'Thuan Hoa Ward',
 'Thuy Xuan Ward',
 'Duong No Ward',
 'Hoa Chau Ward',
 'Hung Loc Ward',
 'Huong An Ward',
 'Huong Thuy Ward',
 'Huong Tra Ward',
 'Khe Tre Ward',
 'Kim Long Ward',
 'Kim Tra Ward',
 'Loc An Ward',
 'Long Quang Ward',
 'Vinh Loc Ward',
 'Vy Da Ward',
 'My Duc Ward',
 'My Hoa Hung Ward',
 'My Thoi Ward',
 'My Thuan Ward',
 'Ngoc Chuc Ward',
 'Nhon Hoi Ward',
 'Nhon My Ward',
 'Nui Cam Ward',
 'O Lam Ward',
 'Oc Eo Ward',
 'Phu An Ward',
 'Phu Hoa Ward',
 'Phu Huu Ward',
 'Phu Lam Ward',
 'Phu Tan Ward',
 'Rach Gia Ward',
 'Son Hai Ward',
 'Son Kien Ward',
 'An Bien Ward',
 'An Chau Ward',
 'An Cu Ward',
 'An Minh Ward',
 'An Phu Ward',
 'Ba Chuc Ward',
 'Binh An Ward',
 'Binh Duc Ward',
 'Binh Giang Ward',
 'Binh Hoa Ward',
 'Binh My Ward',
 'Binh Son Ward',
 'Binh Thanh Dong Ward',
 'Can Dang Ward',
 'Chau Doc Ward',
 'Chau Phong Ward',
 'Chau Phu Ward',
 'Chau Thanh Ward',
 'Chi Lang Ward',
 'Cho Moi Ward',
 'Cho Vam Ward',
 'Co To Ward',
 'Cu Lao Gieng Ward',
 'Kien Hai Ward',
 'Phu Quoc Ward',
 'Tho Chau Ward',
 'Dinh Hoa Ward',
 'Dinh My Ward',
 'Dong Hoa Ward',
 'Dong Hung Ward',
 'Dong Thai Ward',
 'Tan An Ward',
 'Tan Chau Ward',
 'Tan Hiep Ward',
 'Tan Hoi Ward',
 'Tan Thanh Ward',
 'Tay Phu Ward',
 'Tay Yen Ward',
 'Thanh Dong Ward',
 'Thanh Hung Ward',
 'Thanh Loc Ward',
 'Thanh My Tay Ward',
 'Thoai Son Ward',
 'Thoi Son Ward',
 'Tien Hai Ward',
 'Tinh Bien Ward',
 'To Chau Ward',
 'Tri Ton Ward',
 'U Minh Thuong Ward',
 'Van Khanh Ward',
 'Vinh An Ward',
 'Vinh Binh Ward',
 'Vinh Dieu Ward',
 'Vinh Gia Ward',
 'Vinh Hanh Ward',
 'Vinh Hau Ward',
 'Giang Thanh Ward',
 'Giong Rieng Ward',
 'Go Quao Ward',
 'Ha Tien Ward',
 'Hoa Dien Ward',
 'Hoa Hung Ward',
 'Hoa Lac Ward',
 'Hoa Thuan Ward',
 'Hoi An Ward',
 'Hon Dat Ward',
 'Hon Nghe Ward',
 'Khanh Binh Ward',
 'Kien Luong Ward',
 'Long Dien Ward',
 'Long Kien Ward',
 'Long Phu Ward',
 'Long Thanh Ward',
 'Long Xuyen Ward',
 'Vinh Hoa Ward',
 'Vinh Hoa Hung Ward',
 'Vinh Phong Ward',
 'Vinh Te Ward',
 'Vinh Thanh Trung Ward',
 'Vinh Thong Ward',
 'Vinh Thuan Ward',
 'Vinh Trach Ward',
 'Vinh Tuy Ward',
 'Vinh Xuong Ward',
 'My Thai Ward',
 'Nam Duong Ward',
 'Nam Son Ward',
 'Nenh Ward',
 'Nghia Phuong Ward',
 'Ngoc Thien Ward',
 'Nha Nam Ward',
 'Nhan Hoa Ward',
 'Nhan Thang Ward',
 'Ninh Xa Ward',
 'Phat Tich Ward',
 'Phu Khe Ward',
 'Phu Lang Ward',
 'Phuc Hoa Ward',
 'Phuong Lieu Ward',
 'Phuong Son Ward',
 'Quang Trung Ward',
 'Que Vo Ward',
 'Sa Ly Ward',
 'Son Dong Ward',
 'Son Hai Ward',
 'Song Lieu Ward',
 'An Lac Ward',
 'Bac Giang Ward',
 'Bac Lung Ward',
 'Bao Dai Ward',
 'Bien Dong Ward',
 'Bien Son Ward',
 'Bo Ha Ward',
 'Bong Lai Ward',
 'Cam Ly Ward',
 'Canh Thuy Ward',
 'Cao Duc Ward',
 'Chi Lang Ward',
 'Chu Ward',
 'Da Mai Ward',
 'Dai Dong Ward',
 'Dai Lai Ward',
 'Dai Son Ward',
 'Dao Vien Ward',
 'Deo Gia Ward',
 'Dong Cuu Ward',
 'Dong Ky Ward',
 'Dong Nguyen Ward',
 'Dong Phu Ward',
 'Tam Da Ward',
 'Tam Giang Ward',
 'Tam Son Ward',
 'Tam Tien Ward',
 'Tan An Ward',
 'Tan Chi Ward',
 'Tan Dinh Ward',
 'Tan Son Ward',
 'Tan Tien Ward',
 'Tan Yen Ward',
 'Tay Yen Tu Ward',
 'Thuan Thanh Ward',
 'Tien Du Ward',
 'Tien Luc Ward',
 'Tien Phong Ward',
 'Tram Lo Ward',
 'Tri Qua Ward',
 'Trung Chinh Ward',
 'Trung Kenh Ward',
 'Truong Son Ward',
 'Tu Lan Ward',
 'Tu Son Ward',
 'Tuan Dao Ward',
 'Van Ha Ward',
 'Van Mon Ward',
 'Van Son Ward',
 'Viet Yen Ward',
 'Dong Viet Ward',
 'Duong Huu Ward',
 'Gia Binh Ward',
 'Hap Linh Ward',
 'Hiep Hoa Ward',
 'Hoang Van Ward',
 'Hop Thinh Ward',
 'Kep Ward',
 'Kien Lao Ward',
 'Kinh Bac Ward',
 'Lam Thao Ward',
 'Lang Giang Ward',
 'Lien Bao Ward',
 'Luc Nam Ward',
 'Luc Ngan Ward',
 'Luc Son Ward',
 'Luong Tai Ward',
 'Mao Dien Ward',
 'Vo Cuong Ward',
 'Vu Ninh Ward',
 'Xuan Cam Ward',
 'Xuan Luong Ward',
 'Yen Dinh Ward',
 'Yen Dung Ward',
 'Yen Phong Ward',
 'Yen The Ward',
 'Yen Trung Ward',
 'Nam Can Ward',
 'Nguyen Phich Ward',
 'Nguyen Viet Khai Ward',
 'Ninh Quoi Ward',
 'Ninh Thanh Loi Ward',
 'Phan Ngoc Hien Ward',
 'Phong Hiep Ward',
 'Phong Thanh Ward',
 'Phu My Ward',
 'Phu Tan Ward',
 'Phuoc Long Ward',
 'Quach Pham Ward',
 'Song Doc Ward',
 'An Trach Ward',
 'An Xuyen Ward',
 'Bac Lieu Ward',
 'Bien Bach Ward',
 'Cai Doi Vam Ward',
 'Cai Nuoc Ward',
 'Chau Thoi Ward',
 'Da Bac Ward',
 'Dam Doi Ward',
 'Dat Moi Ward',
 'Dat Mui Ward',
 'Dinh Thanh Ward',
 'Dong Hai Ward',
 'Ta An Khuong Ward',
 'Tam Giang Ward',
 'Tan An Ward',
 'Tan Hung Ward',
 'Tan Loc Ward',
 'Tan Thanh Ward',
 'Tan Thuan Ward',
 'Tan Tien Ward',
 'Thanh Tung Ward',
 'Thoi Binh Ward',
 'Tran Phan Ward',
 'Tran Van Thoi Ward',
 'Tri Phai Ward',
 'U Minh Ward',
 'Ganh Hao Ward',
 'Gia Rai Ward',
 'Hiep Thanh Ward',
 'Ho Thi Ky Ward',
 'Hoa Binh Ward',
 'Hoa Thanh Ward',
 'Hong Dan Ward',
 'Hung Hoi Ward',
 'Hung My Ward',
 'Khanh An Ward',
 'Khanh Binh Ward',
 'Khanh Hung Ward',
 'Khanh Lam Ward',
 'Lang Tron Ward',
 'Long Dien Ward',
 'Luong The Tran Ward',
 'Ly Van Lam Ward',
 'Vinh Hau Ward',
 'Vinh Loc Ward',
 'Vinh Loi Ward',
 'Vinh My Ward',
 'Vinh Phuoc Ward',
 'Vinh Thanh Ward',
 'Vinh Trach Ward',
 'Minh Tam Ward',
 'Nam Quang Ward',
 'Nam Tuan Ward',
 'Nguyen Binh Ward',
 'Nguyen Hue Ward',
 'Nung Tri Cao Ward',
 'Phan Thanh Ward',
 'Phuc Hoa Ward',
 'Quang Han Ward',
 'Quang Lam Ward',
 'Quang Long Ward',
 'Quang Trung Ward',
 'Quang Uyen Ward',
 'Son Lo Ward',
 'Bach Dang Ward',
 'Bao Lac Ward',
 'Bao Lam Ward',
 'Be Van Dan Ward',
 'Ca Thanh Ward',
 'Can Yen Ward',
 'Canh Tan Ward',
 'Co Ba Ward',
 'Coc Pang Ward',
 'Dam Thuy Ward',
 'Dinh Phong Ward',
 'Doai Duong Ward',
 'Doc Lap Ward',
 'Dong Khe Ward',
 'Tam Kim Ward',
 'Tan Giang Ward',
 'Thach An Ward',
 'Thanh Cong Ward',
 'Thanh Long Ward',
 'Thong Nong Ward',
 'Thuc Phan Ward',
 'Tinh Tuc Ward',
 'Tong Cot Ward',
 'Tra Linh Ward',
 'Trung Khanh Ward',
 'Truong Ha Ward',
 'Duc Long Ward',
 'Ha Lang Ward',
 'Ha Quang Ward',
 'Hanh Phuc Ward',
 'Hoa An Ward',
 'Hung Dao Ward',
 'Huy Giap Ward',
 'Khanh Xuan Ward',
 'Kim Dong Ward',
 'Lung Nam Ward',
 'Ly Bon Ward',
 'Ly Quoc Ward',
 'Minh Khai Ward',
 'Vinh Quy Ward',
 'Xuan Truong Ward',
 'Yen Tho Ward',
 'Nam Ka Ward',
 'O Loan Ward',
 'Phu Hoa 1 Ward',
 'Phu Hoa 2 Ward',
 'Phu Mo Ward',
 'Phu Xuan Ward',
 'Phu Yen Ward',
 'Pong Drang Ward',
 'Quang Phu Ward',
 'Son Hoa Ward',
 'Son Thanh Ward',
 'Song Cau Ward',
 'Song Hinh Ward',
 'Binh Kien Ward',
 'Buon Don Ward',
 'Buon Ho Ward',
 'Buon Ma Thuot Ward',
 'Cu Bao Ward',
 'Cu M’gar Ward',
 'Cu M’ta Ward',
 'Cu Pong Ward',
 'Cu Prao Ward',
 'Cu Pui Ward',
 'Cu Yang Ward',
 'Cuor Dang Ward',
 'Dak Lieng Ward',
 'Dak Phoi Ward',
 'Dang Kang Ward',
 'Dlie Ya Ward',
 'Dong Hoa Ward',
 'Suoi Trai Ward',
 'Tam Giang Ward',
 'Tan An Ward',
 'Tan Lap Ward',
 'Tan Tien Ward',
 'Tay Hoa Ward',
 'Tay Son Ward',
 'Thanh Nhat Ward',
 'Tuy An Bac Ward',
 'Tuy An Dong Ward',
 'Tuy An Nam Ward',
 'Tuy An Tay Ward',
 'Tuy Hoa Ward',
 'Van Hoa Ward',
 'Dong Xuan Ward',
 'Dray Bhang Ward',
 'Duc Binh Ward',
 'Dur Kmal Ward',
 'Ea Ba Ward',
 'Ea Bung Ward',
 'Ea Drang Ward',
 'Ea Drong Ward',
 'Ea H’Leo Ward',
 'Ea Hiao Ward',
 'Ea Kao Ward',
 'Ea Kar Ward',
 'Ea Khal Ward',
 'Ea Kiet Ward',
 'Ea Kly Ward',
 'Ea Knop Ward',
 'Ea Knuec Ward',
 'Ea Ktur Ward',
 'Ea Ly Ward',
 'Ea M’Droh Ward',
 'Ea Na Ward',
 'Ea Ning Ward',
 'Ea Nuol Ward',
 'Ea O Ward',
 'Ea Pal Ward',
 'Ea Phe Ward',
 'Ea Rieng Ward',
 'Ea Rok Ward',
 'Ea Sup Ward',
 'Ea Trang Ward',
 'Ea Tul Ward',
 'Ea Wer Ward',
 'Ea Wy Ward',
 'Hoa Hiep Ward',
 'Hoa My Ward',
 'Hoa Phu Ward',
 'Hoa Son Ward',
 'Hoa Thinh Ward',
 'Hoa Xuan Ward',
 'Ia Lop Ward',
 'Ia Rve Ward',
 'Krong A Ward',
 'Krong Ana Ward',
 'Krong Bong Ward',
 'Krong Buk Ward',
 'Krong Nang Ward',
 'Krong No Ward',
 'Krong Pac Ward',
 'Lien Son Lak Ward',
 'M’Drak Ward',
 'Vu Bon Ward',
 'Xuan Canh Ward',
 'Xuan Dai Ward',
 'Xuan Lanh Ward',
 'Xuan Loc Ward',
 'Xuan Phuoc Ward',
 'Xuan Tho Ward',
 'Yang Mao Ward',
 'Muong Ang Ward',
 'Muong Cha Ward',
 'Muong Lan Ward',
 'Muong Lay Ward',
 'Muong Luan Ward',
 'Muong Mun Ward',
 'Muong Nha Ward',
 'Muong Nhe Ward',
 'Muong Phang Ward',
 'Muong Pon Ward',
 'Muong Thanh Ward',
 'Muong Toong Ward',
 'Muong Tung Ward',
 'Na Bung Ward',
 'Na Hy Ward',
 'Na Sang Ward',
 'Na Son Ward',
 'Na Tau Ward',
 'Nam Ke Ward',
 'Nam Nen Ward',
 'Nua Ngam Ward',
 'Pa Ham Ward',
 'Phinh Giang Ward',
 'Pu Nhi Ward',
 'Pu Nhung Ward',
 'Quai To Ward',
 'Quang Lam Ward',
 'Sam Mun Ward',
 'Sang Nhe Ward',
 'Si Pa Phin Ward',
 'Sin Chai Ward',
 'Sin Thau Ward',
 'Sinh Phinh Ward',
 'Bung Lao Ward',
 'Cha To Ward',
 'Chieng Sinh Ward',
 'Dien Bien Phu Ward',
 'Thanh An Ward',
 'Thanh Nua Ward',
 'Thanh Yen Ward',
 'Tia Dinh Ward',
 'Tua Chua Ward',
 'Tua Thang Ward',
 'Tuan Giao Ward',
 'Xa Dung Ward',
 'Nam Cat Tien Ward',
 'Nghia Trung Ward',
 'Nha Bich Ward',
 'Nhon Trach Ward',
 'Phu Hoa Ward',
 'Phu Lam Ward',
 'Phu Ly Ward',
 'Phu Nghia Ward',
 'Phu Rieng Ward',
 'Phu Trung Ward',
 'Phu Vinh Ward',
 'Phuoc An Ward',
 'Phuoc Binh Ward',
 'Phuoc Long Ward',
 'Phuoc Son Ward',
 'Phuoc Tan Ward',
 'Phuoc Thai Ward',
 'Song Ray Ward',
 'An Loc Ward',
 'An Phuoc Ward',
 'An Vien Ward',
 'Bao Vinh Ward',
 'Bau Ham Ward',
 'Bien Hoa Ward',
 'Binh An Ward',
 'Binh Loc Ward',
 'Binh Long Ward',
 'Binh Minh Ward',
 'Binh Phuoc Ward',
 'Binh Tan Ward',
 'Bom Bo Ward',
 'Bu Dang Ward',
 'Bu Gia Map Ward',
 'Cam My Ward',
 'Chon Thanh Ward',
 'Da Kia Ward',
 'Dai Phuoc Ward',
 'Dak Lua Ward',
 'Dak Nhau Ward',
 'Dak O Ward',
 'Dau Giay Ward',
 'Dinh Quan Ward',
 'Dong Phu Ward',
 'Dong Tam Ward',
 'Ta Lai Ward',
 'Tam Hiep Ward',
 'Tam Phuoc Ward',
 'Tan An Ward',
 'Tan Hung Ward',
 'Tan Khai Ward',
 'Tan Loi Ward',
 'Tan Phu Ward',
 'Tan Quan Ward',
 'Tan Tien Ward',
 'Tan Trieu Ward',
 'Thanh Son Ward',
 'Thien Hung Ward',
 'Tho Son Ward',
 'Thong Nhat Ward',
 'Thuan Loi Ward',
 'Tran Bien Ward',
 'Trang Bom Ward',
 'Trang Dai Ward',
 'Tri An Ward',
 'Dong Xoai Ward',
 'Gia Kiem Ward',
 'Hang Gon Ward',
 'Ho Nai Ward',
 'Hung Phuoc Ward',
 'Hung Thinh Ward',
 'La Nga Ward',
 'Loc Hung Ward',
 'Loc Ninh Ward',
 'Loc Quang Ward',
 'Loc Tan Ward',
 'Loc Thanh Ward',
 'Loc Thanh Ward',
 'Long Binh Ward',
 'Long Ha Ward',
 'Long Hung Ward',
 'Long Khanh Ward',
 'Long Phuoc Ward',
 'Long Thanh Ward',
 'Minh Duc Ward',
 'Minh Hung Ward',
 'Xuan Bac Ward',
 'Xuan Dinh Ward',
 'Xuan Dong Ward',
 'Xuan Duong Ward',
 'Xuan Hoa Ward',
 'Xuan Lap Ward',
 'Xuan Loc Ward',
 'Xuan Phu Ward',
 'Xuan Que Ward',
 'Xuan Thanh Ward',
 'My An Hung Ward',
 'My Duc Tay Ward',
 'My Hiep Ward',
 'My Loi Ward',
 'My Ngai Ward',
 'My Phong Ward',
 'My Phuoc Tay Ward',
 'My Qui Ward',
 'My Thanh Ward',
 'My Thien Ward',
 'My Tho Ward',
 'My Tho Ward',
 'My Tinh An Ward',
 'My Tra Ward',
 'Ngu Hiep Ward',
 'Nhi Quy Ward',
 'Phong Hoa Ward',
 'Phong My Ward',
 'Phu Cuong Ward',
 'Phu Huu Ward',
 'Phu Thanh Ward',
 'Phu Tho Ward',
 'Phuong Thinh Ward',
 'Sa Dec Ward',
 'Son Qui Ward',
 'An Binh Ward',
 'An Hoa Ward',
 'An Huu Ward',
 'An Long Ward',
 'An Phuoc Ward',
 'An Thanh Thuy Ward',
 'Ba Sao Ward',
 'Binh Hang Trung Ward',
 'Binh Ninh Ward',
 'Binh Phu Ward',
 'Binh Thanh Ward',
 'Binh Trung Ward',
 'Binh Xuan Ward',
 'Cai Be Ward',
 'Cai Lay Ward',
 'Cao Lanh Ward',
 'Chau Thanh Ward',
 'Cho Gao Ward',
 'Dao Thanh Ward',
 'Doc Binh Kieu Ward',
 'Dong Son Ward',
 'Tam Nong Ward',
 'Tan Dien Ward',
 'Tan Dong Ward',
 'Tan Duong Ward',
 'Tan Ho Co Ward',
 'Tan Hoa Ward',
 'Tan Hong Ward',
 'Tan Huong Ward',
 'Tan Khanh Trung Ward',
 'Tan Long Ward',
 'Tan Nhuan Dong Ward',
 'Tan Phu Ward',
 'Tan Phu Dong Ward',
 'Tan Phu Trung Ward',
 'Tan Phuoc 1 Ward',
 'Tan Phuoc 2 Ward',
 'Tan Phuoc 3 Ward',
 'Tan Thanh Ward',
 'Tan Thanh Ward',
 'Tan Thoi Ward',
 'Tan Thuan Binh Ward',
 'Thanh Binh Ward',
 'Thanh Hoa Ward',
 'Thanh Hung Ward',
 'Thanh My Ward',
 'Thanh Phu Ward',
 'Thap Muoi Ward',
 'Thoi Son Ward',
 'Thuong Lac Ward',
 'Thuong Phuoc Ward',
 'Tram Chim Ward',
 'Trung An Ward',
 'Truong Xuan Ward',
 'Vinh Binh Ward',
 'Gia Thuan Ward',
 'Go Cong Ward',
 'Go Cong Dong Ward',
 'Hau My Ward',
 'Hiep Duc Ward',
 'Hoa Long Ward',
 'Hoi Cu Ward',
 'Hong Ngu Ward',
 'Hung Thanh Ward',
 'Kim Son Ward',
 'Lai Vung Ward',
 'Lap Vo Ward',
 'Long Binh Ward',
 'Long Dinh Ward',
 'Long Hung Ward',
 'Long Khanh Ward',
 'Long Phu Thuan Ward',
 'Long Thuan Ward',
 'Long Tien Ward',
 'Luong Hoa Lac Ward',
 'Vinh Huu Ward',
 'Vinh Kim Ward',
 'Ngo May Ward',
 'Nhon Chau Ward',
 'Phu Cat Ward',
 'Phu My Ward',
 'Phu My Bac Ward',
 'Phu My Dong Ward',
 'Phu My Nam Ward',
 'Phu My Tay Ward',
 'Phu Thien Ward',
 'Phu Tuc Ward',
 'Pleiku Ward',
 'Po To Ward',
 'Quy Nhon Ward',
 'Quy Nhon Bac Ward',
 'Quy Nhon Dong Ward',
 'Quy Nhon Nam Ward',
 'Quy Nhon Tay Ward',
 'Son Lang Ward',
 'SRo Ward',
 'Al ba Ward',
 'An Binh Ward',
 'An Hao Ward',
 'An Hoa Ward',
 'An Khe Ward',
 'An Lao Ward',
 'An Luong Ward',
 'An Nhon Ward',
 'An Nhon Bac Ward',
 'An Nhon Dong Ward',
 'An Nhon Nam Ward',
 'An Nhon Tay Ward',
 'An Phu Ward',
 'An Toan Ward',
 'An Tuong Ward',
 'An Vinh Ward',
 'Ayun Ward',
 'Ayun Pa Ward',
 'Bau Can Ward',
 'Bien Ho Ward',
 'Binh An Ward',
 'Binh Dinh Ward',
 'Binh Duong Ward',
 'Binh Hiep Ward',
 'Binh Khe Ward',
 'Binh Phu Ward',
 'Bo Ngoong Ward',
 'Bong Son Ward',
 'Canh Lien Ward',
 'Canh Vinh Ward',
 'Cat Tien Ward',
 'Cho Long Ward',
 'Chu A Thai Ward',
 'Chu Krey Ward',
 'Chu Pah Ward',
 'Chu Prong Ward',
 'Chu Puh Ward',
 'Chu Se Ward',
 'Cuu An Ward',
 'Dak Doa Ward',
 'Dak Po Ward',
 'Dak Rong Ward',
 'Dak Somei Ward',
 'Dak Song Ward',
 'De Gi Ward',
 'Dien Hong Ward',
 'Tam Quan Ward',
 'Tay Son Ward',
 'Thong Nhat Ward',
 'To Tung Ward',
 'Tuy Phuoc Ward',
 'Tuy Phuoc Bac Ward',
 'Tuy Phuoc Dong Ward',
 'Tuy Phuoc Tay Ward',
 'Uar Ward',
 'Van Canh Ward',
 'Van Duc Ward',
 'Duc Co Ward',
 'Gao Ward',
 'Hoa Hoi Ward',
 'Hoai An Ward',
 'Hoai Nhon Ward',
 'Hoai Nhon Bac Ward',
 'Hoai Nhon Dong Ward',
 'Hoai Nhon Nam Ward',
 'Hoai Nhon Tay Ward',
 'Hoi Phu Ward',
 'Hoi Son Ward',
 'Hra Ward',
 'Ia Bang Ward',
 'Ia Boong Ward',
 'Ia Chia Ward',
 'Ia Dok Ward',
 'Ia Dom Ward',
 'Ia Dreh Ward',
 'Ia Grai Ward',
 'Ia Hiao Ward',
 'Ia Hru Ward',
 'Ia Hrung Ward',
 'Ia Khuol Ward',
 'Ia Ko Ward',
 'Ia Krai Ward',
 'Ia Krel Ward',
 'Ia Lau Ward',
 'Ia Le Ward',
 'Ia Ly Ward',
 'Ia Mo Ward',
 'Ia Nan Ward',
 'Ia O Ward',
 'Ia Pa Ward',
 'Ia Phi Ward',
 'Ia Pia Ward',
 'Ia Pnon Ward',
 'Ia Puch Ward',
 'Ia Rbol Ward',
 'Ia Rsai Ward',
 'Ia Sao Ward',
 'Ia Tor Ward',
 'Ia Tul Ward',
 'Kbang Ward',
 'KDang Ward',
 'Kim Son Ward',
 'Kon Chieng Ward',
 'Kon Gang Ward',
 'Kong Bo La Ward',
 'Kong Chro Ward',
 'Krong Ward',
 'Lo Pang Ward',
 'Mang Yang Ward',
 'Vinh Quang Ward',
 'Vinh Son Ward',
 'Vinh Thanh Ward',
 'Vinh Thinh Ward',
 'Xuan An Ward',
 'Ya Hoi Ward',
 'Ya Ma Ward',
 'Nam Hong Linh Ward',
 'Nghi Xuan Ward',
 'Phuc Trach Ward',
 'Son Giang Ward',
 'Son Hong Ward',
 'Son Kim 1 Ward',
 'Son Kim 2 Ward',
 'Son Tay Ward',
 'Son Tien Ward',
 'Song Tri Ward',
 'Bac Hong Linh Ward',
 'Cam Binh Ward',
 'Cam Due Ward',
 'Cam Hung Ward',
 'Cam Lac Ward',
 'Cam Trung Ward',
 'Cam Xuyen Ward',
 'Can Loc Ward',
 'Co Dam Ward',
 'Dan Hai Ward',
 'Dong Kinh Ward',
 'Dong Loc Ward',
 'Thach Ha Ward',
 'Thach Khe Ward',
 'Thach Lac Ward',
 'Thach Xuan Ward',
 'Thanh Sen Ward',
 'Thien Cam Ward',
 'Thuong Duc Ward',
 'Tien Dien Ward',
 'Toan Luu Ward',
 'Tran Phu Ward',
 'Truong Luu Ward',
 'Tu My Ward',
 'Tung Loc Ward',
 'Viet Xuyen Ward',
 'Dong Tien Ward',
 'Duc Dong Ward',
 'Duc Minh Ward',
 'Duc Quang Ward',
 'Duc Thinh Ward',
 'Duc Tho Ward',
 'Gia Hanh Ward',
 'Ha Huy Tap Ward',
 'Ha Linh Ward',
 'Hai Ninh Ward',
 'Hoanh Son Ward',
 'Hong Loc Ward',
 'Huong Binh Ward',
 'Huong Do Ward',
 'Huong Khe Ward',
 'Huong Pho Ward',
 'Huong Son Ward',
 'Huong Xuan Ward',
 'Kim Hoa Ward',
 'Ky Anh Ward',
 'Ky Hoa Ward',
 'Ky Khang Ward',
 'Ky Lac Ward',
 'Ky Thuong Ward',
 'Ky Van Ward',
 'Ky Xuan Ward',
 'Loc Ha Ward',
 'Mai Hoa Ward',
 'Mai Phu Ward',
 'Vu Quang Ward',
 'Vung Ang Ward',
 'Xuan Loc Ward',
 'Yen Hoa Ward',
 'Minh Tho Ward',
 'My Hao Ward',
 'Nam Cuong Ward',
 'Nam Dong Hung Ward',
 'Nam Thai Ninh Ward',
 'Nam Thuy Anh Ward',
 'Nam Tien Hai Ward',
 'Nam Tien Hung Ward',
 'Nghia Dan Ward',
 'Nghia Tru Ward',
 'Ngoc Lam Ward',
 'Ngu Thien Ward',
 'Nguyen Du Ward',
 'Nguyen Trai Ward',
 'Nguyen Van Linh Ward',
 'Nhu Quynh Ward',
 'Pham Ngu Lao Ward',
 'Pho Hien Ward',
 'Phu Duc Ward',
 'Phung Cong Ward',
 'Quang Hung Ward',
 'Quang Lich Ward',
 'Quynh An Ward',
 'Quynh Phu Ward',
 'Son Nam Ward',
 'A Sao Ward',
 'Ai Quoc Ward',
 'An Thi Ward',
 'Bac Dong Hung Ward',
 'Bac Dong Quan Ward',
 'Bac Thai Ninh Ward',
 'Bac Thuy Anh Ward',
 'Bac Tien Hung Ward',
 'Binh Dinh Ward',
 'Binh Nguyen Ward',
 'Binh Thanh Ward',
 'Chau Ninh Ward',
 'Chi Minh Ward',
 'Dai Dong Ward',
 'Dien Ha Ward',
 'Doan Dao Ward',
 'Dong Bang Ward',
 'Dong Chau Ward',
 'Dong Hung Ward',
 'Dong Quan Ward',
 'Dong Thai Ninh Ward',
 'Dong Thuy Anh Ward',
 'Tan Hung Ward',
 'Tan Thuan Ward',
 'Tan Tien Ward',
 'Tay Thai Ninh Ward',
 'Tay Thuy Anh Ward',
 'Tay Tien Hai Ward',
 'Thai Binh Ward',
 'Thai Ninh Ward',
 'Thai Thuy Ward',
 'Than Khe Ward',
 'Thu Tri Ward',
 'Thu Vu Ward',
 'Thuong Hong Ward',
 'Thuy Anh Ward',
 'Tien Hai Ward',
 'Tien Hoa Ward',
 'Tien Hung Ward',
 'Tien La Ward',
 'Tien Lu Ward',
 'Tien Tien Ward',
 'Tong Tran Ward',
 'Tra Giang Ward',
 'Tra Ly Ward',
 'Tran Hung Dao Ward',
 'Tran Lam Ward',
 'Trieu Viet Vuong Ward',
 'Van Giang Ward',
 'Van Xuan Ward',
 'Viet Tien Ward',
 'Viet Yen Ward',
 'Dong Tien Hai Ward',
 'Dong Tien Hung Ward',
 'Duc Hop Ward',
 'Duong Hao Ward',
 'Hiep Cuong Ward',
 'Hoan Long Ward',
 'Hoang Hoa Tham Ward',
 'Hong Chau Ward',
 'Hong Minh Ward',
 'Hong Quang Ward',
 'Hong Vu Ward',
 'Hung Ha Ward',
 'Hung Phu Ward',
 'Khoai Chau Ward',
 'Kien Xuong Ward',
 'Lac Dao Ward',
 'Le Loi Ward',
 'Le Quy Don Ward',
 'Long Hung Ward',
 'Luong Bang Ward',
 'Me So Ward',
 'Vu Phuc Ward',
 'Vu Quy Ward',
 'Vu Thu Ward',
 'Vu Tien Ward',
 'Xuan Truc Ward',
 'Yen My Ward',
 'My Son Ward',
 'Nam Cam Ranh Ward',
 'Nam Khanh Vinh Ward',
 'Nam Nha Trang Ward',
 'Nam Ninh Hoa Ward',
 'Nha Trang Ward',
 'Ninh Chu Ward',
 'Ninh Hai Ward',
 'Ninh Hoa Ward',
 'Ninh Phuoc Ward',
 'Ninh Son Ward',
 'Phan Rang Ward',
 'Phuoc Dinh Ward',
 'Phuoc Ha Ward',
 'Phuoc Hau Ward',
 'Phuoc Huu Ward',
 'Suoi Dau Ward',
 'Suoi Hiep Ward',
 'Anh Dung Ward',
 'Ba Ngoi Ward',
 'Bac Ai Ward',
 'Bac Ai Dong Ward',
 'Bac Ai Tay Ward',
 'Bac Cam Ranh Ward',
 'Bac Khanh Vinh Ward',
 'Bac Nha Trang Ward',
 'Bac Ninh Hoa Ward',
 'Bao An Ward',
 'Ca Na Ward',
 'Cam An Ward',
 'Cam Hiep Ward',
 'Cam Lam Ward',
 'Cam Linh Ward',
 'Cam Ranh Ward',
 'Cong Hai Ward',
 'Truong Sa Ward',
 'Dai Lanh Ward',
 'Dien Dien Ward',
 'Dien Khanh Ward',
 'Dien Lac Ward',
 'Dien Lam Ward',
 'Dien Tho Ward',
 'Do Vinh Ward',
 'Dong Hai Ward',
 'Dong Khanh Son Ward',
 'Dong Ninh Hoa Ward',
 'Tan Dinh Ward',
 'Tay Khanh Son Ward',
 'Tay Khanh Vinh Ward',
 'Tay Nha Trang Ward',
 'Tay Ninh Hoa Ward',
 'Thuan Bac Ward',
 'Thuan Nam Ward',
 'Trung Khanh Vinh Ward',
 'Tu Bong Ward',
 'Van Hung Ward',
 'Van Ninh Ward',
 'Van Thang Ward',
 'Vinh Hai Ward',
 'Hoa Thang Ward',
 'Hoa Tri Ward',
 'Khanh Son Ward',
 'Khanh Vinh Ward',
 'Lam Son Ward',
 'Xuan Hai Ward',
 'Mu Ca Ward',
 'Muong Khoa Ward',
 'Muong Kim Ward',
 'Muong Mo Ward',
 'Muong Te Ward',
 'Muong Than Ward',
 'Nam Cuoi Ward',
 'Nam Hang Ward',
 'Nam Ma Ward',
 'Nam So Ward',
 'Nam Tam Ward',
 'Pa Tan Ward',
 'Pa U Ward',
 'Pac Ta Ward',
 'Phong Tho Ward',
 'Pu Sam Cap Ward',
 'Si Lo Lau Ward',
 'Sin Ho Ward',
 'Sin Suoi Ho Ward',
 'Ban Bo Ward',
 'Binh Lu Ward',
 'Bum Nua Ward',
 'Bum To Ward',
 'Dao San Ward',
 'Doan Ket Ward',
 'Ta Leng Ward',
 'Ta Tong Ward',
 'Tan Phong Ward',
 'Tan Uyen Ward',
 'Than Uyen Ward',
 'Thu Lum Ward',
 'Tua Sin Chai Ward',
 'Hong Thu Ward',
 'Hua Bum Ward',
 'Khoen On Ward',
 'Khong Lao Ward',
 'Khun Ha Ward',
 'Le Loi Ward',
 'Mui Ne Ward',
 'Nam Ban - Lam Ha Ward',
 'Nam Da Ward',
 'Nam Dong Ward',
 'Nam Gia Nghia Ward',
 'Nam Ha - Lam Ha Ward',
 'Nam Nung Ward',
 'Nam Thanh Ward',
 'Nghi Duc Ward',
 'Nhan Co Ward',
 'Ninh Gia Ward',
 'Phan Ri Cua Ward',
 'Phan Son Ward',
 'Phan Thiet Ward',
 'Phu Son - Lam Ha Ward',
 'Phu Thuy Ward',
 'Phuc Tho - Lam Ha Ward',
 'Phuoc Hoi Ward',
 'Quang Hoa Ward',
 'Quang Khe Ward',
 'Quang Lap Ward',
 'Quang Phu Ward',
 'Quang Son Ward',
 'Quang Tan Ward',
 'Quang Tin Ward',
 'Quang Truc Ward',
 'Son Dien Ward',
 'Son My Ward',
 'Song Luy Ward',
 '1 Bao Loc Ward',
 '2 Bao Loc Ward',
 '3 Bao Loc Ward',
 "B' Lao Ward",
 'Bac Binh Ward',
 'Bac Gia Nghia Ward',
 'Bac Ruong Ward',
 'Bao Lam 1 Ward',
 'Bao Lam 2 Ward',
 'Bao Lam 3 Ward',
 'Bao Lam 4 Ward',
 'Bao Lam 5 Ward',
 'Bao Thuan Ward',
 'Binh Thuan Ward',
 'Cam Ly - Da Lat Ward',
 'Cat Tien Ward',
 'Cat Tien 2 Ward',
 'Cat Tien 3 Ward',
 'Cu Jut Ward',
 'Da Huoai Ward',
 'Da Huoai 2 Ward',
 'Da Huoai 3 Ward',
 'Da Teh Ward',
 'Da Teh 2 Ward',
 'Da Teh 3 Ward',
 'Phu Quy Ward',
 'Dak Mil Ward',
 'Dak Sak Ward',
 'Dak Song Ward',
 'Dak Wil Ward',
 'Dam Rong 1 Ward',
 'Dam Rong 2 Ward',
 'Dam Rong 3 Ward',
 'Dam Rong 4 Ward',
 'Di Linh Ward',
 'Dinh Trang Thuong Ward',
 'Dinh Van - Lam Ha Ward',
 'Don Duong Ward',
 'Dong Gia Nghia Ward',
 'Dong Giang Ward',
 'Dong Kho Ward',
 'Suoi Kiet Ward',
 'Ta Dung Ward',
 'Ta Hine Ward',
 'Ta Nang Ward',
 'Tan Ha -  Lam Ha Ward',
 'Tan Hai Ward',
 'Tan Hoi Ward',
 'Tan Lap Ward',
 'Tan Minh Ward',
 'Tan Thanh Ward',
 'Tanh Linh Ward',
 'Thuan An Ward',
 'Thuan Hanh Ward',
 'Tien Thanh Ward',
 'Tra Tan Ward',
 'Truong Xuan Ward',
 'Tuy Duc Ward',
 'Tuy Phong Ward',
 'Tuyen Quang Ward',
 'Vinh Hao Ward',
 "D'Ran Ward",
 'Duc An Ward',
 'Duc Lap Ward',
 'Duc Linh Ward',
 'Duc Trong Ward',
 'Gia Hiep Ward',
 'Hai Ninh Ward',
 'Ham Kiem Ward',
 'Ham Liem Ward',
 'Ham Tan Ward',
 'Ham Thang Ward',
 'Ham Thanh Ward',
 'Ham Thuan Ward',
 'Ham Thuan Bac Ward',
 'Ham Thuan Nam Ward',
 'Hiep Thanh Ward',
 'Hoa Bac Ward',
 'Hoa Ninh Ward',
 'Hoa Thang Ward',
 'Hoai Duc Ward',
 'Hong Son Ward',
 'Hong Thai Ward',
 'Ka Do Ward',
 'Kien Duc Ward',
 'Krong No Ward',
 'La Da Ward',
 'La Gi Ward',
 'Lac Duong Ward',
 'Lam Vien - Da Lat Ward',
 'LangBiang - Da Lat Ward',
 'Lien Huong Ward',
 'Luong Son Ward',
 'Xuan Huong - Da Lat Ward',
 'Xuan Truong - Da Lat Ward',
 'Na Duong Ward',
 'Na Sam Ward',
 'Nhan Ly Ward',
 'Nhat Hoa Ward',
 'Quan Son Ward',
 'Quoc Khanh Ward',
 'Quoc Viet Ward',
 'Quy Hoa Ward',
 'Ba Son Ward',
 'Bac Son Ward',
 'Bang Mac Ward',
 'Binh Gia Ward',
 'Cai Kinh Ward',
 'Cao Loc Ward',
 'Chau Son Ward',
 'Chi Lang Ward',
 'Chien Thang Ward',
 'Cong Son Ward',
 'Diem He Ward',
 'Dinh Lap Ward',
 'Doan Ket Ward',
 'Dong Dang Ward',
 'Dong Kinh Ward',
 'Tam Thanh Ward',
 'Tan Doan Ward',
 'Tan Thanh Ward',
 'Tan Tien Ward',
 'Tan Tri Ward',
 'Tan Van Ward',
 'Thai Binh Ward',
 'That Khe Ward',
 'Thien Hoa Ward',
 'Thien Long Ward',
 'Thien Tan Ward',
 'Thien Thuat Ward',
 'Thong Nhat Ward',
 'Thuy Hung Ward',
 'Trang Dinh Ward',
 'Tri Le Ward',
 'Tuan Son Ward',
 'Van Lang Ward',
 'Van Linh Ward',
 'Van Nham Ward',
 'Van Quan Ward',
 'Hoa Tham Ward',
 'Hoang Van Thu Ward',
 'Hoi Hoan Ward',
 'Hong Phong Ward',
 'Hung Vu Ward',
 'Huu Lien Ward',
 'Huu Lung Ward',
 'Khang Chien Ward',
 'Khanh Khe Ward',
 'Khuat Xa Ward',
 'Kien Moc Ward',
 'Ky Lua Ward',
 'Loc Binh Ward',
 'Loi Bac Ward',
 'Luong Van Tri Ward',
 'Mau Son Ward',
 'Vu Lang Ward',
 'Vu Le Ward',
 'Xuan Duong Ward',
 'Yen Binh Ward',
 'Yen Phuc Ward',
 'Mo Vang Ward',
 'Mu Cang Chai Ward',
 'Muong Bo Ward',
 'Muong Hum Ward',
 'Muong Khuong Ward',
 'Muong Lai Ward',
 'Nam Chay Ward',
 'Nam Co Ward',
 'Nam Cuong Ward',
 'Nam Xe Ward',
 'Nghia Do Ward',
 'Nghia Lo Ward',
 'Nghia Tam Ward',
 'Ngu Chi Son Ward',
 'Pha Long Ward',
 'Phinh Ho Ward',
 'Phong Du Ha Ward',
 'Phong Du Thuong Ward',
 'Phong Hai Ward',
 'Phuc Khanh Ward',
 'Phuc Loi Ward',
 'Pung Luong Ward',
 'Quy Mong Ward',
 'Sa Pa Ward',
 'Si Ma Cai Ward',
 'Sin Cheng Ward',
 'Son Luong Ward',
 'A Mu Sung Ward',
 'Au Lau Ward',
 'Bac Ha Ward',
 'Ban Ho Ward',
 'Ban Lau Ward',
 'Ban Lien Ward',
 'Ban Xeo Ward',
 'Bao Ai Ward',
 'Bao Ha Ward',
 'Bao Nhai Ward',
 'Bao Thang Ward',
 'Bao Yen Ward',
 'Bat Xat Ward',
 'Cam Duong Ward',
 'Cam Nhan Ward',
 'Cao Son Ward',
 'Cat Thinh Ward',
 'Cau Thia Ward',
 'Chan Thinh Ward',
 'Chau Que Ward',
 'Che Tao Ward',
 'Chieng Ken Ward',
 'Coc Lau Ward',
 'Coc San Ward',
 'Den Sang Ward',
 'Dong Cuong Ward',
 'Ta Cu Ty Ward',
 'Ta Phin Ward',
 'Ta Van Ward',
 'Ta Xi Lang Ward',
 'Tan Hop Ward',
 'Tan Linh Ward',
 'Tang Loong Ward',
 'Thac Ba Ward',
 'Thuong Bang La Ward',
 'Thuong Ha Ward',
 'Tram Tau Ward',
 'Tran Yen Ward',
 'Trinh Tuong Ward',
 'Trung Tam Ward',
 'Tu Le Ward',
 'Van Ban Ward',
 'Van Chan Ward',
 'Van Phu Ward',
 'Viet Hong Ward',
 'Duong Quy Ward',
 'Gia Hoi Ward',
 'Gia Phu Ward',
 'Hanh Phuc Ward',
 'Hop Thanh Ward',
 'Hung Khanh Ward',
 'Khanh Hoa Ward',
 'Khanh Yen Ward',
 'Khao Mang Ward',
 'Lam Giang Ward',
 'Lam Thuong Ward',
 'Lao Cai Ward',
 'Lao Chai Ward',
 'Lien Son Ward',
 'Luc Yen Ward',
 'Lung Phinh Ward',
 'Luong Thinh Ward',
 'Mau A Ward',
 'Minh Luong Ward',
 'Vo Lao Ward',
 'Xuan Ai Ward',
 'Xuan Hoa Ward',
 'Xuan Quang Ward',
 'Y Ty Ward',
 'Yen Bai Ward',
 'Yen Binh Ward',
 'Yen Thanh Ward',
 'Mon Son Ward',
 'Muong Chong Ward',
 'Muong Ham Ward',
 'Muong Long Ward',
 'Muong Quang Ward',
 'Muong Tip Ward',
 'Muong Xen Ward',
 'My Ly Ward',
 'Na Loi Ward',
 'Na Ngoi Ward',
 'Nam Can Ward',
 'Nam Dan Ward',
 'Nga My Ward',
 'Nghi Loc Ward',
 'Nghia Dan Ward',
 'Nghia Dong Ward',
 'Nghia Hanh Ward',
 'Nghia Hung Ward',
 'Nghia Khanh Ward',
 'Nghia Lam Ward',
 'Nghia Loc Ward',
 'Nghia Mai Ward',
 'Nghia Tho Ward',
 'Nhan Hoa Ward',
 'Nhon Mai Ward',
 'Phuc Loc Ward',
 'Quan Thanh Ward',
 'Quang Chau Ward',
 'Quang Dong Ward',
 'Que Phong Ward',
 'Quy Chau Ward',
 'Quy Hop Ward',
 'Quynh Anh Ward',
 'Quynh Luu Ward',
 'Quynh Mai Ward',
 'Quynh Phu Ward',
 'Quynh Son Ward',
 'Quynh Tam Ward',
 'Quynh Thang Ward',
 'Quynh Van Ward',
 'Son Lam Ward',
 'An Chau Ward',
 'Anh Son Ward',
 'Anh Son Dong Ward',
 'Bac Ly Ward',
 'Bach Ha Ward',
 'Bach Ngoc Ward',
 'Bich Hao Ward',
 'Binh Chuan Ward',
 'Binh Minh Ward',
 'Cam Phuc Ward',
 'Cat Ngan Ward',
 'Chau Binh Ward',
 'Chau Hong Ward',
 'Chau Khe Ward',
 'Chau Loc Ward',
 'Chau Tien Ward',
 'Chieu Luu Ward',
 'Con Cuong Ward',
 'Cua Lo Ward',
 'Dai Dong Ward',
 'Dai Hue Ward',
 'Dien Chau Ward',
 'Do Luong Ward',
 'Dong Hieu Ward',
 'Dong Loc Ward',
 'Dong Thanh Ward',
 'Tam Dong Ward',
 'Tam Hop Ward',
 'Tam Quang Ward',
 'Tam Thai Ward',
 'Tan An Ward',
 'Tan Chau Ward',
 'Tan Ky Ward',
 'Tan Mai Ward',
 'Tan Phu Ward',
 'Tay Hieu Ward',
 'Thai Hoa Ward',
 'Than Linh Ward',
 'Thanh Binh Tho Ward',
 'Thanh Vinh Ward',
 'Thien Nhan Ward',
 'Thong Thu Ward',
 'Thuan Trung Ward',
 'Tien Dong Ward',
 'Tien Phong Ward',
 'Tri Le Ward',
 'Trung Loc Ward',
 'Truong Vinh Ward',
 'Tuong Duong Ward',
 'Van An Ward',
 'Van Du Ward',
 'Van Hien Ward',
 'Van Kieu Ward',
 'Van Tu Ward',
 'Duc Chau Ward',
 'Giai Lac Ward',
 'Giai Xuan Ward',
 'Hai Chau Ward',
 'Hai Loc Ward',
 'Hanh Lam Ward',
 'Hoa Quan Ward',
 'Hoang Mai Ward',
 'Hop Minh Ward',
 'Hung Chan Ward',
 'Hung Chau Ward',
 'Hung Nguyen Ward',
 'Hung Nguyen Nam Ward',
 'Huoi Tu Ward',
 'Huu Khuong Ward',
 'Huu Kiem Ward',
 'Keng Du Ward',
 'Kim Bang Ward',
 'Kim Lien Ward',
 'Lam Thanh Ward',
 'Luong Minh Ward',
 'Luong Son Ward',
 'Mau Thach Ward',
 'Minh Chau Ward',
 'Minh Hop Ward',
 'Vinh Hung Ward',
 'Vinh Loc Ward',
 'Vinh Phu Ward',
 'Vinh Tuong Ward',
 'Xuan Lam Ward',
 'Yen Hoa Ward',
 'Yen Na Ward',
 'Yen Thanh Ward',
 'Yen Trung Ward',
 'Yen Xuan Ward',
 'Minh Tan Ward',
 'Minh Thai Ward',
 'My Loc Ward',
 'Nam Dinh Ward',
 'Nam Dong Ward',
 'Nam Hoa Lu Ward',
 'Nam Hong Ward',
 'Nam Ly Ward',
 'Nam Minh Ward',
 'Nam Ninh Ward',
 'Nam Truc Ward',
 'Nam Xang Ward',
 'Nghia Hung Ward',
 'Nghia Lam Ward',
 'Nghia Son Ward',
 'Nguyen Uy Ward',
 'Nhan Ha Ward',
 'Nho Quan Ward',
 'Ninh Cuong Ward',
 'Ninh Giang Ward',
 'Phat Diem Ward',
 'Phong Doanh Ward',
 'Phu Long Ward',
 'Phu Ly Ward',
 'Phu Son Ward',
 'Phu Van Ward',
 'Quang Hung Ward',
 'Quang Thien Ward',
 'Quy Nhat Ward',
 'Quynh Luu Ward',
 'Rang Dong Ward',
 'Bac Ly Ward',
 'Binh An Ward',
 'Binh Giang Ward',
 'Binh Luc Ward',
 'Binh Minh Ward',
 'Binh My Ward',
 'Binh Son Ward',
 'Cat Thanh Ward',
 'Chat Binh Ward',
 'Chau Son Ward',
 'Co Le Ward',
 'Cuc Phuong Ward',
 'Dai Hoang Ward',
 'Dinh Hoa Ward',
 'Dong A Ward',
 'Dong Hoa Lu Ward',
 'Dong Thai Ward',
 'Dong Thinh Ward',
 'Tam Chuc Ward',
 'Tam Diep Ward',
 'Tan Minh Ward',
 'Tan Thanh Ward',
 'Tay Hoa Lu Ward',
 'Thanh Binh Ward',
 'Thanh Lam Ward',
 'Thanh Liem Ward',
 'Thanh Nam Ward',
 'Thanh Son Ward',
 'Thien Truong Ward',
 'Tien Son Ward',
 'Tran Thuong Ward',
 'Truc Ninh Ward',
 'Trung Son Ward',
 'Truong Thi Ward',
 'Van Thang Ward',
 'Vi Khe Ward',
 'Dong Van Ward',
 'Duy Ha Ward',
 'Duy Tan Ward',
 'Duy Tien Ward',
 'Gia Hung Ward',
 'Gia Lam Ward',
 'Gia Phong Ward',
 'Gia Tran Ward',
 'Gia Tuong Ward',
 'Gia Van Ward',
 'Gia Vien Ward',
 'Giao Binh Ward',
 'Giao Hoa Ward',
 'Giao Hung Ward',
 'Giao Minh Ward',
 'Giao Ninh Ward',
 'Giao Phuc Ward',
 'Giao Thuy Ward',
 'Ha Nam Ward',
 'Hai An Ward',
 'Hai Anh Ward',
 'Hai Hau Ward',
 'Hai Hung Ward',
 'Hai Quang Ward',
 'Hai Thinh Ward',
 'Hai Tien Ward',
 'Hai Xuan Ward',
 'Hien Khanh Ward',
 'Hoa Lu Ward',
 'Hong Phong Ward',
 'Hong Quang Ward',
 'Khanh Hoi Ward',
 'Khanh Nhac Ward',
 'Khanh Thien Ward',
 'Khanh Trung Ward',
 'Kim Bang Ward',
 'Kim Dong Ward',
 'Kim Son Ward',
 'Kim Thanh Ward',
 'Lai Thanh Ward',
 'Le Ho Ward',
 'Liem Ha Ward',
 'Liem Tuyen Ward',
 'Lien Minh Ward',
 'Ly Nhan Ward',
 'Ly Thuong Kiet Ward',
 'Vinh Tru Ward',
 'Vu Ban Ward',
 'Vu Duong Ward',
 'Xuan Giang Ward',
 'Xuan Hong Ward',
 'Xuan Hung Ward',
 'Xuan Truong Ward',
 'Y Yen Ward',
 'Yen Cuong Ward',
 'Yen Dong Ward',
 'Yen Khanh Ward',
 'Yen Mac Ward',
 'Yen Mo Ward',
 'Yen Son Ward',
 'Yen Thang Ward',
 'Yen Tu Ward',
 'Muong Bi Ward',
 'Muong Dong Ward',
 'Muong Hoa Ward',
 'Muong Thang Ward',
 'Muong Vang Ward',
 'Nat Son Ward',
 'Ngoc Son Ward',
 'Nguyet Duc Ward',
 'Nhan Nghia Ward',
 'Nong Trang Ward',
 'Pa Co Ward',
 'Phong Chau Ward',
 'Phu Khe Ward',
 'Phu My Ward',
 'Phu Ninh Ward',
 'Phu Tho Ward',
 'Phuc Yen Ward',
 'Phung Nguyen Ward',
 'Quang Yen Ward',
 'Quy Duc Ward',
 'Quyet Thang Ward',
 'Son Dong Ward',
 'Son Luong Ward',
 'Song Lo Ward',
 'An Binh Ward',
 'An Nghia Ward',
 'Au Co Ward',
 'Ban Nguyen Ward',
 'Bang Luan Ward',
 'Bao La Ward',
 'Binh Nguyen Ward',
 'Binh Phu Ward',
 'Binh Tuyen Ward',
 'Binh Xuyen Ward',
 'Cam Khe Ward',
 'Cao Duong Ward',
 'Cao Phong Ward',
 'Cao Son Ward',
 'Chan Mong Ward',
 'Chi Dam Ward',
 'Chi Tien Ward',
 'Cu Dong Ward',
 'Da Bac Ward',
 'Dai Dinh Ward',
 'Dai Dong Ward',
 'Dan Chu Ward',
 'Dan Thuong Ward',
 'Dao Tru Ward',
 'Dao Xa Ward',
 'Doan Hung Ward',
 'Dong Luong Ward',
 'Dong Thanh Ward',
 'Tam Dao Ward',
 'Tam Duong Ward',
 'Tam Duong Bac Ward',
 'Tam Hong Ward',
 'Tam Nong Ward',
 'Tam Son Ward',
 'Tan Hoa Ward',
 'Tan Lac Ward',
 'Tan Mai Ward',
 'Tan Pheo Ward',
 'Tan Son Ward',
 'Tay Coc Ward',
 'Te Lo Ward',
 'Thai Hoa Ward',
 'Thanh Ba Ward',
 'Thanh Mieu Ward',
 'Thanh Son Ward',
 'Thanh Thuy Ward',
 'Thinh Minh Ward',
 'Tho Tang Ward',
 'Tho Van Ward',
 'Thong Nhat Ward',
 'Thu Cuc Ward',
 'Thung Nai Ward',
 'Thuong Coc Ward',
 'Thuong Long Ward',
 'Tien Lu Ward',
 'Tien Luong Ward',
 'Tien Phong Ward',
 'Toan Thang Ward',
 'Tram Than Ward',
 'Trung Son Ward',
 'Tu Vu Ward',
 'Van Ban Ward',
 'Van Lang Ward',
 'Van Mieu Ward',
 'Van Phu Ward',
 'Van Son Ward',
 'Van Xuan Ward',
 'Viet Tri Ward',
 'Vinh An Ward',
 'Vinh Chan Ward',
 'Duc Nhan Ward',
 'Dung Tien Ward',
 'Ha Hoa Ward',
 'Hai Luu Ward',
 'Hien Luong Ward',
 'Hien Quan Ward',
 'Hoa Binh Ward',
 'Hoang An Ward',
 'Hoang Cuong Ward',
 'Hoi Thinh Ward',
 'Hop Kim Ward',
 'Hop Ly Ward',
 'Hung Viet Ward',
 'Huong Can Ward',
 'Hy Cuong Ward',
 'Kha Cuu Ward',
 'Kim Boi Ward',
 'Ky Son Ward',
 'Lac Luong Ward',
 'Lac Son Ward',
 'Lac Thuy Ward',
 'Lai Dong Ward',
 'Lam Thao Ward',
 'Lap Thach Ward',
 'Lien Chau Ward',
 'Lien Hoa Ward',
 'Lien Minh Ward',
 'Lien Son Ward',
 'Long Coc Ward',
 'Luong Son Ward',
 'Mai Chau Ward',
 'Mai Ha Ward',
 'Minh Dai Ward',
 'Minh Hoa Ward',
 'Vinh Hung Ward',
 'Vinh Phu Ward',
 'Vinh Phuc Ward',
 'Vinh Thanh Ward',
 'Vinh Tuong Ward',
 'Vinh Yen Ward',
 'Vo Mieu Ward',
 'Xuan Dai Ward',
 'Xuan Hoa Ward',
 'Xuan Lang Ward',
 'Xuan Lung Ward',
 'Xuan Vien Ward',
 'Yen Ky Ward',
 'Yen Lac Ward',
 'Yen Lang Ward',
 'Yen Lap Ward',
 'Yen Phu Ward',
 'Yen Son Ward',
 'Yen Thuy Ward',
 'Yen Tri Ward',
 'Mo Cay Ward',
 'Mo Duc Ward',
 'Mo Rai Ward',
 'Nghia Giang Ward',
 'Nghia Hanh Ward',
 'Nghia Lo Ward',
 'Ngoc Linh Ward',
 'Ngok Bay Ward',
 'Ngok Reo Ward',
 'Ngok Tu Ward',
 'Nguyen Nghiem Ward',
 'Phuoc Giang Ward',
 'Ro Koi Ward',
 'Sa Binh Ward',
 'Sa Huynh Ward',
 'Sa Loong Ward',
 'Sa Thay Ward',
 'Son Ha Ward',
 'Son Ha Ward',
 'Son Ky Ward',
 'Son Linh Ward',
 'Son Mai Ward',
 'Son Tay Ward',
 'Son Tay Ha Ward',
 'Son Tay Thuong Ward',
 'Son Thuy Ward',
 'Son Tinh Ward',
 'An Phu Ward',
 'Ba Dinh Ward',
 'Ba Dong Ward',
 'Ba Gia Ward',
 'Ba To Ward',
 'Ba To Ward',
 'Ba Vi Ward',
 'Ba Vinh Ward',
 'Ba Xa Ward',
 'Binh Chuong Ward',
 'Binh Minh Ward',
 'Binh Son Ward',
 'Bo Y Ward',
 'Ca Dam Ward',
 'Cam Thanh Ward',
 'Ly Son Ward',
 'Dak Bla Ward',
 'Dak Cam Ward',
 'Dak Ha Ward',
 'Dak Koi Ward',
 'Dak Long Ward',
 'Dak Mar Ward',
 'Dak Mon Ward',
 'Dak Pek Ward',
 'Dak Plo Ward',
 'Dak Pxi Ward',
 'Dak Ro Wa Ward',
 'Dak Rve Ward',
 'Dak Sao Ward',
 'Dak To Ward',
 'Dak To Kan Ward',
 'Dak Ui Ward',
 'Dang Thuy Tram Ward',
 'Dinh Cuong Ward',
 'Dong Son Ward',
 'Tay Tra Ward',
 'Tay Tra Bong Ward',
 'Thanh Bong Ward',
 'Thien Tin Ward',
 'Tho Phong Ward',
 'Tinh Khe Ward',
 'Tra Bong Ward',
 'Tra Cau Ward',
 'Tra Giang Ward',
 'Truong Giang Ward',
 'Truong Quang Trong Ward',
 'Tu Mo Rong Ward',
 'Tu Nghia Ward',
 'Van Tuong Ward',
 'Ve Giang Ward',
 'Dong Tra Bong Ward',
 'Duc Nong Ward',
 'Duc Pho Ward',
 'Ia Chim Ward',
 'Ia Dal Ward',
 'Ia Toi Ward',
 'Khanh Cuong Ward',
 'Kon Braih Ward',
 'Kon Dao Ward',
 'Kon Plong Ward',
 'Kon Tum Ward',
 'Lan Phong Ward',
 'Long Phung Ward',
 'Mang But Ward',
 'Mang Den Ward',
 'Mang Ri Ward',
 'Minh Long Ward',
 'Xop Ward',
 'Ya Ly Ward',
 'Mong Cai 1 Ward',
 'Mong Cai 2 Ward',
 'Mong Cai 3 Ward',
 'Mong Duong Ward',
 'Phong Coc Ward',
 'Quang Duc Ward',
 'Quang Ha Ward',
 'Quang Hanh Ward',
 'Quang La Ward',
 'Quang Tan Ward',
 'Quang Yen Ward',
 'An Sinh Ward',
 'Ba Che Ward',
 'Bai Chay Ward',
 'Binh Khe Ward',
 'Binh Lieu Ward',
 'Cai Chien Ward',
 'Cam Pha Ward',
 'Cao Xanh Ward',
 'Cua Ong Ward',
 'Co To Ward',
 'Van Don Ward',
 'Dam Ha Ward',
 'Dien Xa Ward',
 'Dong Mai Ward',
 'Dong Ngu Ward',
 'Thong Nhat Ward',
 'Tien Yen Ward',
 'Tuan Chau Ward',
 'Uong Bi Ward',
 'Vang Danh Ward',
 'Viet Hung Ward',
 'Dong Trieu Ward',
 'Duong Hoa Ward',
 'Ha An Ward',
 'Ha Lam Ward',
 'Ha Long Ward',
 'Ha Tu Ward',
 'Hai Hoa Ward',
 'Hai Lang Ward',
 'Hai Ninh Ward',
 'Hai Son Ward',
 'Hiep Hoa Ward',
 'Hoang Que Ward',
 'Hoanh Bo Ward',
 'Hoanh Mo Ward',
 'Hong Gai Ward',
 'Ky Thuong Ward',
 'Lien Hoa Ward',
 'Luc Hon Ward',
 'Luong Minh Ward',
 'Mao Khe Ward',
 'Vinh Thuc Ward',
 'Yen Tu Ward',
 'My Thuy Ward',
 'Nam Ba Don Ward',
 'Nam Cua Viet Ward',
 'Nam Dong Ha Ward',
 'Nam Gianh Ward',
 'Nam Hai Lang Ward',
 'Nam Trach Ward',
 'Ninh Chau Ward',
 'Phong Nha Ward',
 'Phu Trach Ward',
 'Quang Ninh Ward',
 'Quang Trach Ward',
 'Quang Tri Ward',
 'Sen Ngu Ward',
 'A Doi Ward',
 'Ai Tu Ward',
 'Ba Don Ward',
 'Ba Long Ward',
 'Bac Gianh Ward',
 'Bac Trach Ward',
 'Ben Hai Ward',
 'Ben Quan Ward',
 'Bo Trach Ward',
 'Cam Hong Ward',
 'Cam Lo Ward',
 'Con Tien Ward',
 'Cua Tung Ward',
 'Cua Viet Ward',
 'Con Co Ward',
 'Dakrong Ward',
 'Dan Hoa Ward',
 'Dien Sanh Ward',
 'Dong Ha Ward',
 'Dong Hoi Ward',
 'Dong Le Ward',
 'Dong Son Ward',
 'Dong Thuan Ward',
 'Ta Rut Ward',
 'Tan Gianh Ward',
 'Tan Lap Ward',
 'Tan My Ward',
 'Tan Thanh Ward',
 'Thuong Trach Ward',
 'Trieu Binh Ward',
 'Trieu Co Ward',
 'Trieu Phong Ward',
 'Trung Thuan Ward',
 'Truong Ninh Ward',
 'Truong Phu Ward',
 'Truong Son Ward',
 'Tuyen Binh Ward',
 'Tuyen Hoa Ward',
 'Tuyen Lam Ward',
 'Tuyen Phu Ward',
 'Tuyen Son Ward',
 'Vinh Dinh Ward',
 'Dong Trach Ward',
 'Gio Linh Ward',
 'Hai Lang Ward',
 'Hieu Giang Ward',
 'Hoa Trach Ward',
 'Hoan Lao Ward',
 'Huong Hiep Ward',
 'Huong Lap Ward',
 'Huong Phung Ward',
 'Khe Sanh Ward',
 'Kim Dien Ward',
 'Kim Ngan Ward',
 'Kim Phu Ward',
 'La Lay Ward',
 'Lao Bao Ward',
 'Le Ninh Ward',
 'Le Thuy Ward',
 'Lia Ward',
 'Minh Hoa Ward',
 'Vinh Hoang Ward',
 'Vinh Linh Ward',
 'Vinh Thuy Ward',
 'Moc Chau Ward',
 'Moc Son Ward',
 'Muoi Noi Ward',
 'Muong Bam Ward',
 'Muong Bang Ward',
 'Muong Bu Ward',
 'Muong Chanh Ward',
 'Muong Chien Ward',
 'Muong Coi Ward',
 'Muong E Ward',
 'Muong Gion Ward',
 'Muong Hung Ward',
 'Muong Khieng Ward',
 'Muong La Ward',
 'Muong Lam Ward',
 'Muong Lan Ward',
 'Muong Leo Ward',
 'Muong Sai Ward',
 'Nam Lau Ward',
 'Nam Ty Ward',
 'Ngoc Chien Ward',
 'Pac Nga Ward',
 'Phieng Cam Ward',
 'Phieng Khoai Ward',
 'Phieng Pan Ward',
 'Phu Yen Ward',
 'Pung Banh Ward',
 'Quynh Nhai Ward',
 'Song Khua Ward',
 'Song Ma Ward',
 'Sop Cop Ward',
 'Bac Yen Ward',
 'Binh Thuan Ward',
 'Bo Sinh Ward',
 'Chieng An Ward',
 'Chieng Coi Ward',
 'Chieng Hac Ward',
 'Chieng Hoa Ward',
 'Chieng Khoong Ward',
 'Chieng Khuong Ward',
 'Chieng La Ward',
 'Chieng Lao Ward',
 'Chieng Mai Ward',
 'Chieng Mung Ward',
 'Chieng Sai Ward',
 'Chieng Sinh Ward',
 'Chieng So Ward',
 'Chieng Son Ward',
 'Chieng Sung Ward',
 'Co Ma Ward',
 'Doan Ket Ward',
 'Suoi To Ward',
 'Ta Hoc Ward',
 'Ta Khoa Ward',
 'Ta Xua Ward',
 'Tan Phong Ward',
 'Tan Yen Ward',
 'Thao Nguyen Ward',
 'Thuan Chau Ward',
 'To Hieu Ward',
 'To Mua Ward',
 'Tuong Ha Ward',
 'Van Ho Ward',
 'Van Son Ward',
 'Gia Phu Ward',
 'Huoi Mot Ward',
 'Kim Bon Ward',
 'Long He Ward',
 'Long Phieng Ward',
 'Long Sap Ward',
 'Mai Son Ward',
 'Xim Vang Ward',
 'Xuan Nha Ward',
 'Yen Chau Ward',
 'Yen Son Ward',
 'Moc Hoa Ward',
 'My An Ward',
 'My Hanh Ward',
 'My Le Ward',
 'My Loc Ward',
 'My Quy Ward',
 'My Thanh Ward',
 'My Yen Ward',
 'Nhon Hoa Lap Ward',
 'Nhon Ninh Ward',
 'Nhut Tao Ward',
 'Ninh Dien Ward',
 'Ninh Thanh Ward',
 'Phuoc Chi Ward',
 'Phuoc Ly Ward',
 'Phuoc Thanh Ward',
 'Phuoc Vinh Ward',
 'Phuoc Vinh Tay Ward',
 'Rach Kien Ward',
 'An Luc Long Ward',
 'An Ninh Ward',
 'An Tinh Ward',
 'Ben Cau Ward',
 'Ben Luc Ward',
 'Binh Duc Ward',
 'Binh Hiep Ward',
 'Binh Hoa Ward',
 'Binh Minh Ward',
 'Binh Thanh Ward',
 'Can Duoc Ward',
 'Can Giuoc Ward',
 'Cau Khoi Ward',
 'Chau Thanh Ward',
 'Dong Thanh Ward',
 'Tam Vu Ward',
 'Tan An Ward',
 'Tan Bien Ward',
 'Tan Chau Ward',
 'Tan Dong Ward',
 'Tan Hoa Ward',
 'Tan Hoi Ward',
 'Tan Hung Ward',
 'Tan Lan Ward',
 'Tan Lap Ward',
 'Tan Long Ward',
 'Tan Ninh Ward',
 'Tan Phu Ward',
 'Tan Tap Ward',
 'Tan Tay Ward',
 'Tan Thanh Ward',
 'Tan Thanh Ward',
 'Tan Tru Ward',
 'Thanh Binh Ward',
 'Thanh Dien Ward',
 'Thanh Duc Ward',
 'Thanh Hoa Ward',
 'Thanh Loi Ward',
 'Thanh Phuoc Ward',
 'Thu Thua Ward',
 'Thuan My Ward',
 'Tra Vong Ward',
 'Trang Bang Ward',
 'Truong Mit Ward',
 'Tuyen Binh Ward',
 'Tuyen Thanh Ward',
 'Vam Co Ward',
 'Vinh Chau Ward',
 'Vinh Cong Ward',
 'Duc Hoa Ward',
 'Duc Hue Ward',
 'Duc Lap Ward',
 'Duong Minh Chau Ward',
 'Gia Loc Ward',
 'Go Dau Ward',
 'Hao Duoc Ward',
 'Hau Nghia Ward',
 'Hau Thanh Ward',
 'Hiep Hoa Ward',
 'Hoa Hoi Ward',
 'Hoa Khanh Ward',
 'Hoa Thanh Ward',
 'Hung Dien Ward',
 'Hung Thuan Ward',
 'Khanh Hau Ward',
 'Khanh Hung Ward',
 'Kien Tuong Ward',
 'Loc Ninh Ward',
 'Long An Ward',
 'Long Cang Ward',
 'Long Chu Ward',
 'Long Hoa Ward',
 'Long Huu Ward',
 'Long Thuan Ward',
 'Luong Hoa Ward',
 'Vinh Hung Ward',
 'Vinh Thanh Ward',
 'Na Phac Ward',
 'Na Ri Ward',
 'Nam Cuong Ward',
 'Nam Hoa Ward',
 'Ngan Son Ward',
 'Nghia Ta Ward',
 'Nghien Loan Ward',
 'Nghinh Tuong Ward',
 'Phan Dinh Phung Ward',
 'Pho Yen Ward',
 'Phong Quang Ward',
 'Phu Binh Ward',
 'Phu Dinh Ward',
 'Phu Lac Ward',
 'Phu Luong Ward',
 'Phu Thinh Ward',
 'Phu Thong Ward',
 'Phu Xuyen Ward',
 'Phuc Loc Ward',
 'Phuc Thuan Ward',
 'Phuong Tien Ward',
 'Quan Chu Ward',
 'Quan Trieu Ward',
 'Quang Bach Ward',
 'Quang Son Ward',
 'Quyet Thang Ward',
 'Sang Moc Ward',
 'Song Cong Ward',
 'An Khanh Ward',
 'Ba Be Ward',
 'Ba Xuyen Ward',
 'Bac Kan Ward',
 'Bach Quang Ward',
 'Bach Thong Ward',
 'Bang Thanh Ward',
 'Bang Van Ward',
 'Binh Thanh Ward',
 'Binh Yen Ward',
 'Cam Giang Ward',
 'Cao Minh Ward',
 'Cho Don Ward',
 'Cho Moi Ward',
 'Cho Ra Ward',
 'Con Minh Ward',
 'Cuong Loi Ward',
 'Dai Phuc Ward',
 'Dai Tu Ward',
 'Dan Tien Ward',
 'Diem Thuy Ward',
 'Dinh Hoa Ward',
 'Dong Hy Ward',
 'Dong Phuc Ward',
 'Tan Cuong Ward',
 'Tan Khanh Ward',
 'Tan Ky Ward',
 'Tan Thanh Ward',
 'Than Sa Ward',
 'Thanh Cong Ward',
 'Thanh Mai Ward',
 'Thanh Thinh Ward',
 'Thuong Minh Ward',
 'Thuong Quan Ward',
 'Tich Luong Ward',
 'Trai Cau Ward',
 'Tran Phu Ward',
 'Trang Xa Ward',
 'Trung Hoi Ward',
 'Trung Thanh Ward',
 'Van Han Ward',
 'Van Lang Ward',
 'Van Lang Ward',
 'Van Phu Ward',
 'Van Xuan Ward',
 'Duc Luong Ward',
 'Duc Xuan Ward',
 'Gia Sang Ward',
 'Hiep Luc Ward',
 'Hop Thanh Ward',
 'Kha Son Ward',
 'Kim Phuong Ward',
 'La Bang Ward',
 'La Hien Ward',
 'Lam Vy Ward',
 'Linh Son Ward',
 'Vinh Thong Ward',
 'Vo Nhai Ward',
 'Vo Tranh Ward',
 'Xuan Duong Ward',
 'Yen Binh Ward',
 'Yen Phong Ward',
 'Yen Thinh Ward',
 'Yen Trach Ward',
 'Minh Son Ward',
 'Muong Chanh Ward',
 'Muong Lat Ward',
 'Muong Ly Ward',
 'Muong Min Ward',
 'Na Meo Ward',
 'Nam Sam Son Ward',
 'Nam Xuan Ward',
 'Nga An Ward',
 'Nga Son Ward',
 'Nga Thang Ward',
 'Nghi Son Ward',
 'Ngoc Lac Ward',
 'Ngoc Lien Ward',
 'Ngoc Son Ward',
 'Ngoc Trao Ward',
 'Nguyet An Ward',
 'Nguyet Vien Ward',
 'Nhi Son Ward',
 'Nhu Thanh Ward',
 'Nhu Xuan Ward',
 'Nong Cong Ward',
 'Phu Le Ward',
 'Phu Xuan Ward',
 'Pu Luong Ward',
 'Pu Nhi Ward',
 'Quan Son Ward',
 'Quang Binh Ward',
 'Quang Chieu Ward',
 'Quang Chinh Ward',
 'Quang Ngoc Ward',
 'Quang Ninh Ward',
 'Quang Phu Ward',
 'Quang Trung Ward',
 'Quang Yen Ward',
 'Quy Loc Ward',
 'Quy Luong Ward',
 'Sam Son Ward',
 'Sao Vang Ward',
 'Son Dien Ward',
 'Son Thuy Ward',
 'An Nong Ward',
 'Ba Dinh Ward',
 'Ba Thuoc Ward',
 'Bat Mot Ward',
 'Bien Thuong Ward',
 'Bim Son Ward',
 'Cac Son Ward',
 'Cam Tan Ward',
 'Cam Thach Ward',
 'Cam Thuy Ward',
 'Cam Tu Ward',
 'Cam Van Ward',
 'Co Lung Ward',
 'Cong Chinh Ward',
 'Dao Duy Tu Ward',
 'Dien Lu Ward',
 'Dien Quang Ward',
 'Dinh Hoa Ward',
 'Dinh Tan Ward',
 'Dong Luong Ward',
 'Dong Quang Ward',
 'Dong Son Ward',
 'Dong Thanh Ward',
 'Tam Chung Ward',
 'Tam Lu Ward',
 'Tam Thanh Ward',
 'Tan Dan Ward',
 'Tan Ninh Ward',
 'Tan Thanh Ward',
 'Tan Tien Ward',
 'Tay Do Ward',
 'Thach Binh Ward',
 'Thach Lap Ward',
 'Thach Quang Ward',
 'Thang Binh Ward',
 'Thang Loc Ward',
 'Thang Loi Ward',
 'Thanh Ky Ward',
 'Thanh Phong Ward',
 'Thanh Quan Ward',
 'Thanh Vinh Ward',
 'Thien Phu Ward',
 'Thiet Ong Ward',
 'Thieu Hoa Ward',
 'Thieu Quang Ward',
 'Thieu Tien Ward',
 'Thieu Toan Ward',
 'Thieu Trung Ward',
 'Tho Binh Ward',
 'Tho Lap Ward',
 'Tho Long Ward',
 'Tho Ngoc Ward',
 'Tho Phu Ward',
 'Tho Xuan Ward',
 'Thuong Ninh Ward',
 'Thuong Xuan Ward',
 'Tien Trang Ward',
 'Tinh Gia Ward',
 'Tong Son Ward',
 'Trieu Loc Ward',
 'Trieu Son Ward',
 'Truc Lam Ward',
 'Trung Chinh Ward',
 'Trung Ha Ward',
 'Trung Ly Ward',
 'Trung Son Ward',
 'Trung Thanh Ward',
 'Truong Lam Ward',
 'Truong Van Ward',
 'Tuong Linh Ward',
 'Van Du Ward',
 'Van Loc Ward',
 'Van Nho Ward',
 'Van Phu Ward',
 'Van Xuan Ward',
 'Dong Tien Ward',
 'Giao An Ward',
 'Ha Long Ward',
 'Ha Trung Ward',
 'Hac Thanh Ward',
 'Hai Binh Ward',
 'Hai Linh Ward',
 'Ham Rong Ward',
 'Hau Loc Ward',
 'Hien Kiet Ward',
 'Ho Vuong Ward',
 'Hoa Loc Ward',
 'Hoa Quy Ward',
 'Hoang Chau Ward',
 'Hoang Giang Ward',
 'Hoang Hoa Ward',
 'Hoang Loc Ward',
 'Hoang Phu Ward',
 'Hoang Son Ward',
 'Hoang Thanh Ward',
 'Hoang Tien Ward',
 'Hoat Giang Ward',
 'Hoi Xuan Ward',
 'Hop Tien Ward',
 'Kien Tho Ward',
 'Kim Tan Ward',
 'Lam Son Ward',
 'Linh Son Ward',
 'Linh Toai Ward',
 'Luan Thanh Ward',
 'Luong Son Ward',
 'Luu Ve Ward',
 'Mau Lam Ward',
 'Vinh Loc Ward',
 'Xuan Binh Ward',
 'Xuan Chinh Ward',
 'Xuan Du Ward',
 'Xuan Hoa Ward',
 'Xuan Lap Ward',
 'Xuan Thai Ward',
 'Xuan Tin Ward',
 'Yen Dinh Ward',
 'Yen Khuong Ward',
 'Yen Nhan Ward',
 'Yen Ninh Ward',
 'Yen Phu Ward',
 'Yen Thang Ward',
 'Yen Tho Ward',
 'Yen Truong Ward',
 'Minh Quang Ward',
 'Minh Son Ward',
 'Minh Tan Ward',
 'Minh Thanh Ward',
 'Minh Xuan Ward',
 'My Lam Ward',
 'Na Hang Ward',
 'Nam Dan Ward',
 'Nam Dich Ward',
 'Nghia Thuan Ward',
 'Ngoc Duong Ward',
 'Ngoc Long Ward',
 'Nhu Khe Ward',
 'Niem Son Ward',
 'Nong Tien Ward',
 'Pa Vay Su Ward',
 'Pho Bang Ward',
 'Phu Linh Ward',
 'Phu Luong Ward',
 'Phu Luu Ward',
 'Po Ly Ngai Ward',
 'Quan Ba Ward',
 'Quang Binh Ward',
 'Quang Nguyen Ward',
 'Sa Phin Ward',
 'Son Duong Ward',
 'Son Thuy Ward',
 'Son Vi Ward',
 'Sung Mang Ward',
 'An Tuong Ward',
 'Bac Me Ward',
 'Bac Quang Ward',
 'Bach Dich Ward',
 'Bach Ngoc Ward',
 'Bach Xa Ward',
 'Ban May Ward',
 'Bang Hanh Ward',
 'Bang Lang Ward',
 'Binh An Ward',
 'Binh Ca Ward',
 'Binh Thuan Ward',
 'Binh Xa Ward',
 'Can Ty Ward',
 'Cao Bo Ward',
 'Chiem Hoa Ward',
 'Con Lon Ward',
 'Dong Tam Ward',
 'Dong Tho Ward',
 'Tan An Ward',
 'Tan Long Ward',
 'Tan My Ward',
 'Tan Quang Ward',
 'Tan Thanh Ward',
 'Tan Tien Ward',
 'Tan Trao Ward',
 'Tan Trinh Ward',
 'Tat Nga Ward',
 'Thai Binh Ward',
 'Thai Hoa Ward',
 'Thai Son Ward',
 'Thang Mo Ward',
 'Thang Tin Ward',
 'Thanh Thuy Ward',
 'Thong Nguyen Ward',
 'Thuan Hoa Ward',
 'Thuong Lam Ward',
 'Thuong Nong Ward',
 'Thuong Son Ward',
 'Tien Nguyen Ward',
 'Tien Yen Ward',
 'Tri Phu Ward',
 'Trung Ha Ward',
 'Trung Son Ward',
 'Trung Thinh Ward',
 'Truong Sinh Ward',
 'Tung Ba Ward',
 'Tung Vai Ward',
 'Vi Xuyen Ward',
 'Viet Lam Ward',
 'Dong Van Ward',
 'Dong Yen Ward',
 'Du Gia Ward',
 'Duong Hong Ward',
 'Duong Thuong Ward',
 'Giap Trung Ward',
 'Ha Giang 1 Ward',
 'Ha Giang 2 Ward',
 'Ham Yen Ward',
 'Ho Thau Ward',
 'Hoa An Ward',
 'Hoang Su Phi Ward',
 'Hong Son Ward',
 'Hong Thai Ward',
 'Hung An Ward',
 'Hung Duc Ward',
 'Hung Loi Ward',
 'Khau Vai Ward',
 'Khuon Lung Ward',
 'Kien Dai Ward',
 'Kien Thiet Ward',
 'Kim Binh Ward',
 'Lam Binh Ward',
 'Lao Chai Ward',
 'Lien Hiep Ward',
 'Linh Ho Ward',
 'Luc Hanh Ward',
 'Lung Cu Ward',
 'Lung Phin Ward',
 'Lung Tam Ward',
 'Mau Due Ward',
 'Meo Vac Ward',
 'Minh Ngoc Ward',
 'Vinh Tuy Ward',
 'Xin Man Ward',
 'Xuan Giang Ward',
 'Xuan Van Ward',
 'Yen Cuong Ward',
 'Yen Hoa Ward',
 'Yen Lap Ward',
 'Yen Minh Ward',
 'Yen Nguyen Ward',
 'Yen Phu Ward',
 'Yen Son Ward',
 'Yen Thanh Ward',
 'Mo Cay Ward',
 'My Chanh Hoa Ward',
 'My Long Ward',
 'My Thuan Ward',
 'Ngai Tu Ward',
 'Ngu Lac Ward',
 'Nguyet Hoa Ward',
 'Nhi Long Ward',
 'Nhi Truong Ward',
 'Nhon Phu Ward',
 'Nhuan Phu Tan Ward',
 'Phong Thanh Ward',
 'Phu Khuong Ward',
 'Phu Phung Ward',
 'Phu Quoi Ward',
 'Phu Tan Ward',
 'Phu Thuan Ward',
 'Phu Tuc Ward',
 'Phuoc Hau Ward',
 'Phuoc Long Ward',
 'Phuoc My Trung Ward',
 'Quoi An Ward',
 'Quoi Dien Ward',
 'Quoi Thien Ward',
 'Son Dong Ward',
 'Song Loc Ward',
 'Song Phu Ward',
 'An Binh Ward',
 'An Dinh Ward',
 'An Hiep Ward',
 'An Hoi Ward',
 'An Ngai Trung Ward',
 'An Phu Tan Ward',
 'An Qui Ward',
 'An Truong Ward',
 'Ba Tri Ward',
 'Bao Thanh Ward',
 'Ben Tre Ward',
 'Binh Dai Ward',
 'Binh Minh Ward',
 'Binh Phu Ward',
 'Binh Phuoc Ward',
 'Cai Ngang Ward',
 'Cai Nhum Ward',
 'Cai Von Ward',
 'Cang Long Ward',
 'Cau Ke Ward',
 'Cau Ngang Ward',
 'Chau Hoa Ward',
 'Chau Hung Ward',
 'Chau Thanh Ward',
 'Cho Lach Ward',
 'Dai An Ward',
 'Dai Dien Ward',
 'Don Chau Ward',
 'Dong Hai Ward',
 'Dong Khoi Ward',
 'Dong Thanh Ward',
 'Tam Binh Ward',
 'Tam Ngai Ward',
 'Tan An Ward',
 'Tan Hanh Ward',
 'Tan Hao Ward',
 'Tan Hoa Ward',
 'Tan Long Hoi Ward',
 'Tan Luoc Ward',
 'Tan Ngai Ward',
 'Tan Phu Ward',
 'Tan Quoi Ward',
 'Tan Thanh Binh Ward',
 'Tan Thuy Ward',
 'Tan Xuan Ward',
 'Tap Ngai Ward',
 'Tap Son Ward',
 'Thanh Duc Ward',
 'Thanh Hai Ward',
 'Thanh Phong Ward',
 'Thanh Phu Ward',
 'Thanh Phuoc Ward',
 'Thanh Thoi Ward',
 'Thanh Tri Ward',
 'Thoi Thuan Ward',
 'Tien Thuy Ward',
 'Tieu Can Ward',
 'Tra Con Ward',
 'Tra Cu Ward',
 'Tra On Ward',
 'Tra Vinh Ward',
 'Trung Hiep Ward',
 'Trung Ngai Ward',
 'Trung Thanh Ward',
 'Truong Long Hoa Ward',
 'Duyen Hai Ward',
 'Giao Long Ward',
 'Giong Trom Ward',
 'Ham Giang Ward',
 'Hiep My Ward',
 'Hieu Phung Ward',
 'Hieu Thanh Ward',
 'Hoa Binh Ward',
 'Hoa Hiep Ward',
 'Hoa Minh Ward',
 'Hoa Thuan Ward',
 'Hung Hoa Ward',
 'Hung Khanh Trung Ward',
 'Hung My Ward',
 'Hung Nhuong Ward',
 'Huong My Ward',
 'Loc Thuan Ward',
 'Long Chau Ward',
 'Long Duc Ward',
 'Long Hiep Ward',
 'Long Ho Ward',
 'Long Hoa Ward',
 'Long Huu Ward',
 'Long Thanh Ward',
 'Long Vinh Ward',
 'Luc Si Thanh Ward',
 'Luong Hoa Ward',
 'Luong Phu Ward',
 'Luu Nghiep Anh Ward',
 'Vinh Kim Ward',
 'Vinh Thanh Ward',
 'Vinh Xuan Ward']
def make_ward_aliases(wards):
    alias_dict = {}

    for canonical in wards:
        base = canonical.replace(" Ward", "").strip()

        aliases = {
            canonical,
            base,

            f"{base} Ward",
            f"Ward {base}",

            f"Phuong {base}",
            f"Phường {base}",
            f"P {base}",
            f"P. {base}",

            f"Xa {base}",
            f"Xã {base}",
            f"X {base}",
            f"X. {base}",

            f"Thi tran {base}",
            f"Thị trấn {base}",
            f"TT {base}",
            f"TT. {base}",
        }

        alias_dict[canonical] = sorted(aliases)

    return alias_dict


ward_old_to_new_alias = make_ward_aliases(wards)

__all__ = ["banks", "provinces", "wards"]
